// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct ShopContractProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for ShopContractProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = ShopContractProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        ShopContractProxyMethods { wrapped_tx: tx }
    }
}

pub struct ShopContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> ShopContractProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ShopContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ShopContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn register_shop<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg5: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
        category: Arg1,
        location: Arg2,
        description: Arg3,
        image_url: Arg4,
        website: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerShop")
            .argument(&slug)
            .argument(&category)
            .argument(&location)
            .argument(&description)
            .argument(&image_url)
            .argument(&website)
            .original_result()
    }

    pub fn update_shop<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg5: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
        category: Arg1,
        location: Arg2,
        description: Arg3,
        image_url: Arg4,
        website: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("updateShop")
            .argument(&slug)
            .argument(&category)
            .argument(&location)
            .argument(&description)
            .argument(&image_url)
            .argument(&website)
            .original_result()
    }

    pub fn get_shop_info<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ShopInfo<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getShopInfo")
            .argument(&slug)
            .original_result()
    }

    pub fn get_shop_count(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, usize> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getShopCount")
            .original_result()
    }

    pub fn get_shops<
        Arg0: ProxyArg<usize>,
        Arg1: ProxyArg<usize>,
    >(
        self,
        offset: Arg0,
        limit: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, MultiValue2<ManagedBuffer<Env::Api>, ShopInfo<Env::Api>>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getShops")
            .argument(&offset)
            .argument(&limit)
            .original_result()
    }

    pub fn get_shops_by_category<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<usize>,
        Arg2: ProxyArg<usize>,
    >(
        self,
        category: Arg0,
        offset: Arg1,
        limit: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, MultiValue2<ManagedBuffer<Env::Api>, ShopInfo<Env::Api>>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getShopsByCategory")
            .argument(&category)
            .argument(&offset)
            .argument(&limit)
            .original_result()
    }

    pub fn add_service<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<u64>,
        Arg4: ProxyArg<u32>,
        Arg5: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg6: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        shop_slug: Arg0,
        service_slug: Arg1,
        name: Arg2,
        price: Arg3,
        duration_minutes: Arg4,
        category: Arg5,
        description: Arg6,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("addService")
            .argument(&shop_slug)
            .argument(&service_slug)
            .argument(&name)
            .argument(&price)
            .argument(&duration_minutes)
            .argument(&category)
            .argument(&description)
            .original_result()
    }

    pub fn remove_service<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        shop_slug: Arg0,
        service_slug: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("removeService")
            .argument(&shop_slug)
            .argument(&service_slug)
            .original_result()
    }

    pub fn get_services<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        shop_slug: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, ShopService<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getServices")
            .argument(&shop_slug)
            .original_result()
    }

    pub fn add_product<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<u64>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg5: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        shop_slug: Arg0,
        product_slug: Arg1,
        name: Arg2,
        price: Arg3,
        category: Arg4,
        description: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("addProduct")
            .argument(&shop_slug)
            .argument(&product_slug)
            .argument(&name)
            .argument(&price)
            .argument(&category)
            .argument(&description)
            .original_result()
    }

    pub fn update_product_stock<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<bool>,
    >(
        self,
        shop_slug: Arg0,
        product_slug: Arg1,
        in_stock: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("updateProductStock")
            .argument(&shop_slug)
            .argument(&product_slug)
            .argument(&in_stock)
            .original_result()
    }

    pub fn remove_product<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        shop_slug: Arg0,
        product_slug: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("removeProduct")
            .argument(&shop_slug)
            .argument(&product_slug)
            .original_result()
    }

    pub fn get_products<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        shop_slug: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, ShopProduct<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getProducts")
            .argument(&shop_slug)
            .original_result()
    }

    pub fn set_payment_destination<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
        chain: Arg1,
        address: Arg2,
        token: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setPaymentDestination")
            .argument(&slug)
            .argument(&chain)
            .argument(&address)
            .argument(&token)
            .original_result()
    }

    pub fn get_payment_destination<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, PaymentDestination<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPaymentDestination")
            .argument(&slug)
            .original_result()
    }
}

#[type_abi]
#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode, Clone)]
pub struct ShopInfo<Api>
where
    Api: ManagedTypeApi,
{
    pub owner: ManagedAddress<Api>,
    pub created_at: u64,
    pub category: ManagedBuffer<Api>,
    pub location: ManagedBuffer<Api>,
    pub description: ManagedBuffer<Api>,
    pub image_url: ManagedBuffer<Api>,
    pub website: ManagedBuffer<Api>,
}

#[type_abi]
#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode, Clone)]
pub struct ShopService<Api>
where
    Api: ManagedTypeApi,
{
    pub slug: ManagedBuffer<Api>,
    pub name: ManagedBuffer<Api>,
    pub price: u64,
    pub duration_minutes: u32,
    pub category: ManagedBuffer<Api>,
    pub description: ManagedBuffer<Api>,
}

#[type_abi]
#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode, Clone)]
pub struct ShopProduct<Api>
where
    Api: ManagedTypeApi,
{
    pub slug: ManagedBuffer<Api>,
    pub name: ManagedBuffer<Api>,
    pub price: u64,
    pub category: ManagedBuffer<Api>,
    pub description: ManagedBuffer<Api>,
    pub in_stock: bool,
}

#[type_abi]
#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode, Clone)]
pub struct PaymentDestination<Api>
where
    Api: ManagedTypeApi,
{
    pub chain: ManagedBuffer<Api>,
    pub address: ManagedBuffer<Api>,
    pub token: ManagedBuffer<Api>,
}
