// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    form
    (
        init => init
        upgrade => upgrade
        createForm => create_form
        updateForm => update_form
        setCompleteMessage => set_complete_message
        setActive => set_active
        recordSubmission => record_submission
        getForm => get_form
        getFormsByAgent => get_forms_by_agent
        getAllForms => get_all_forms
        addField => add_field
        updateField => update_field
        removeField => remove_field
        getFields => get_fields
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
