// This file is auto-generated by scripts/generate-warp-types.js

export type TypeformGetResponsesInputs = {
  FORM_ID: string;
  page_size: number;
};

export type TypeformGetResponsesData = {
  RESPONSES: any;
  COUNT: any;
};

export type TypeformListFormsInputs = {
  page: number;
  page_size: number;
};

export type TypeformListFormsData = {
  FORMS: any;
  COUNT: any;
};
