// This file is auto-generated by scripts/generate-warp-types.js

export type TypeformListFormsInputs = {
  page: number;
  page_size: number;
};

export type TypeformListFormsData = {
  FORMS: any;
  COUNT: any;
};
