// This file is auto-generated by scripts/generate-warp-types.js

export type CouponCreateInputs = {
  collectionId: string;
  code: string;
  discountPercent: string;
  maxUses: string;
  expiryDays: string;
};

export type CouponCreateData = {
  COUPON_ID: any;
};
