// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleMapsPlaceDetailsInputs = {
  PLACE_ID: string;
};

export type GoogleMapsPlaceDetailsData = {
  ID: any;
  NAME: any;
  ADDRESS: any;
  PHONE: any;
  PHONE_INTL: any;
  WEBSITE: any;
  RATING: any;
  REVIEW_COUNT: number;
  STATUS: string;
  TYPES: any;
  HOURS: any;
};

export type GoogleMapsPlacesTextSearchInputs = {
  textQuery: string;
  regionCode: string;
  languageCode: string;
  pageSize: number;
  pageToken: string;
};

export type GoogleMapsPlacesTextSearchData = {
  PLACES: any;
  NEXT_PAGE_TOKEN: any;
};
