// This file is auto-generated by scripts/generate-warp-types.js

export type ReplicateGetPredictionInputs = {
  PREDICTION_ID: string;
};

export type ReplicateGetPredictionData = {
  ID: any;
  STATUS: string;
  OUTPUT: any;
  ERROR: any;
  METRICS: any;
};

export type ReplicateRunModelInputs = {
  version: string;
  input: string;
};

export type ReplicateRunModelData = {
  ID: any;
  STATUS: string;
  OUTPUT: any;
};

export type ReplicateSearchModelsInputs = {
  query: string;
};

export type ReplicateSearchModelsData = {
  MODELS: any;
  COUNT: any;
};
