// This file is auto-generated by scripts/generate-warp-types.js

export type FollowupsBirthdayScanInputs = {
};

export type FollowupsBirthdayScanData = {
  CONTACTS: any;
};

export type FollowupsBirthdayInputs = {
  contactId: string;
  offer: string;
  integrationType: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type FollowupsBirthdayData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type FollowupsCheckInInputs = {
  contactId: string;
  lastVisitDate: string;
  integrationType: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type FollowupsCheckInData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type FollowupsInactiveScanInputs = {
};

export type FollowupsInactiveScanData = {
  _DATA: any;
};

export type FollowupsPostTreatmentInputs = {
  contactId: string;
  treatment: string;
  integrationType: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type FollowupsPostTreatmentData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type FollowupsReorderReminderInputs = {
  contactId: string;
  productName: string;
  lastPurchased: string;
  integrationType: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type FollowupsReorderReminderData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type FollowupsWinBackInputs = {
  contactId: string;
  daysInactive: string;
  offer: string;
  integrationType: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type FollowupsWinBackData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};
