// This file is auto-generated by scripts/generate-warp-types.js

export type PDFRenderfromHTMLInputs = {
  html: string;
  label: string;
  fileName: string;
};

export type PDFRenderfromHTMLData = {
  url: any;
  name: any;
  id: any;
  mime: any;
};
