// This file is auto-generated by scripts/generate-warp-types.js

export type CursorAddFollowupInputs = {
  AGENT_ID: string;
  followupInstruction: string;
};

export type CursorAddFollowupData = {
  AGENT_ID: any;
};

export type CursorDeleteAgentInputs = {
  AGENT_ID: string;
};

export type CursorDeleteAgentData = {
  AGENT_ID: any;
};

export type CursorGetAgentStatusInputs = {
  AGENT_ID: string;
};

export type CursorGetAgentStatusData = {
  AGENT_ID: any;
  AGENT_NAME: any;
  AGENT_STATUS: any;
  REPOSITORY: any;
  BRANCH_NAME: any;
  AGENT_URL: any;
  PR_URL: any;
  SUMMARY: any;
};

export type CursorGetAgentConversationInputs = {
  AGENT_ID: string;
};

export type CursorGetAgentConversationData = {
  AGENT_ID: any;
  MESSAGES: any;
};

export type CursorGetAPIKeyInfoInputs = {
};

export type CursorGetAPIKeyInfoData = {
  API_KEY_NAME: any;
  CREATED_AT: any;
  USER_EMAIL: any;
};

export type CursorLaunchAgentInputs = {
  task: string;
  repository: string;
  baseBranch: string;
  model: string;
  autoCreatePr: boolean;
  openAsCursorGithubApp: boolean;
  skipReviewerRequest: boolean;
  branchName: string;
  webhookUrl: string;
  webhookSecret: string;
};

export type CursorLaunchAgentData = {
  AGENT_ID: any;
  AGENT_NAME: any;
  AGENT_STATUS: any;
  AGENT_URL: any;
};

export type CursorListAgentsInputs = {
  limit: number;
  cursor: string;
};

export type CursorListAgentsData = {
  AGENTS: any;
  NEXT_CURSOR: any;
};

export type CursorListModelsInputs = {
};

export type CursorListModelsData = {
  MODELS: any;
};

export type CursorListRepositoriesInputs = {
};

export type CursorListRepositoriesData = {
  REPOSITORIES: any;
};

export type CursorStopAgentInputs = {
  AGENT_ID: string;
};

export type CursorStopAgentData = {
  AGENT_ID: any;
};
