// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXCreateNFTInputs = {
  COLLECTION_ID: string;
  QUANTITY: string;
  NFT_NAME: string;
  ROYALTIES: string;
  HASH: string;
  ATTRIBUTES: string;
  URI: string;
};

export type MultiversXCreateNFTData = {
  TX_HASH: string;
  NFT_IDENTIFIER: any;
  NFT_NAME: any;
  QUANTITY: any;
};
