// This file is auto-generated by scripts/generate-warp-types.js

export type helloCashCreateInvoiceInputs = {
  recipientname: string;
  recipientemail: string;
  invoicedate: string;
  paymentmethod: string;
};

export type helloCashCreateInvoiceData = {
  INVOICE_ID: any;
  INVOICE: any;
};

export type helloCashGetInvoiceInputs = {
  INVOICE_ID: string;
};

export type helloCashGetInvoiceData = {
  INVOICE: any;
};

export type helloCashListArticlesInputs = {
  limit: number;
  search: string;
};

export type helloCashListArticlesData = {
  ARTICLES: any;
};

export type helloCashListCustomersInputs = {
  limit: number;
  search: string;
};

export type helloCashListCustomersData = {
  CUSTOMERS: any;
};

export type helloCashListInvoicesInputs = {
  limit: number;
  showDetails: string;
};

export type helloCashListInvoicesData = {
  INVOICES: any;
};
