// This file is auto-generated by scripts/generate-warp-types.js

export type VercelListDeploymentsInputs = {
  limit: number;
  projectId: string;
};

export type VercelListDeploymentsData = {
  DEPLOYMENTS: any;
  COUNT: any;
};
