// This file is auto-generated by scripts/generate-warp-types.js

export type TodoistGetTasksInputs = {
  project_id: string;
  filter: string;
};

export type TodoistGetTasksData = {
  TASKS: any;
  COUNT: any;
};
