// This file is auto-generated by scripts/generate-warp-types.js

export type TodoistCreateTaskInputs = {
  content: string;
  description: string;
  due_string: string;
};

export type TodoistCreateTaskData = {
  TASK_ID: any;
  CONTENT: any;
  URL: any;
};

export type TodoistGetTasksInputs = {
  project_id: string;
  filter: string;
};

export type TodoistGetTasksData = {
  TASKS: any;
  COUNT: any;
};
