// This file is auto-generated by scripts/generate-warp-types.js

export type RedditSearchInputs = {
  q: string;
  restrict_sr: string;
  sort: string;
  t: string;
  limit: string;
};

export type RedditSearchData = {
  RAW_OUT: any;
  RESULTS: any;
  RESULT_COUNT: number;
  RESULTS_SUMMARY: any[];
};
