// This file is auto-generated by scripts/generate-warp-types.js

export type RedditCreateCommentInputs = {
  parent: string;
  text: string;
};

export type RedditCreateCommentData = {
  COMMENT_ID: any;
  COMMENT_NAME: any;
  COMMENT_BODY: any;
};

export type RedditCreatePostInputs = {
  sr: string;
  title: string;
  text: string;
  url: string;
  kind: string;
  sendreplies: string;
  nsfw: string;
  spoiler: string;
};

export type RedditCreatePostData = {
  POST_ID: any;
  POST_NAME: any;
  POST_URL: any;
  POST_PERMALINK: any;
};

export type RedditGetCommentsInputs = {
  SUBREDDIT: string;
  POST_ID: string;
  sort: string;
  limit: string;
  depth: string;
};

export type RedditGetCommentsData = {
  COMMENTS: any[];
  COMMENT_COUNT: number;
  COMMENTS_SUMMARY: any[];
};

export type RedditGetPostDetailsInputs = {
  SUBREDDIT: string;
  POST_ID: string;
};

export type RedditGetPostDetailsData = {
  POST_DATA: any;
  POST_TITLE: string;
  POST_AUTHOR: string;
  POST_SCORE: number;
  POST_UPS: number;
  POST_DOWNS: number;
  POST_NUM_COMMENTS: number;
  POST_SELFTEXT: string;
  POST_URL: string;
  POST_PERMALINK: string;
  POST_CREATED_UTC: number;
};

export type RedditGetPostsInputs = {
  SUBREDDIT: string;
  SORT: string;
  limit: string;
  after: string;
};

export type RedditGetPostsData = {
  POSTS: any[];
  POST_COUNT: number;
  AFTER: any;
  POSTS_SUMMARY: any[];
};

export type RedditGetUserInfoInputs = {
  USERNAME: string;
};

export type RedditGetUserInfoData = {
  USER_DATA: any;
  USERNAME: string;
  KARMA: number;
  LINK_KARMA: number;
  COMMENT_KARMA: number;
  ACCOUNT_CREATED_UTC: number;
  ACCOUNT_AGE_DAYS: number;
  IS_GOLD: boolean;
  IS_VERIFIED: boolean;
  POST_KARMA: number;
};

export type RedditSearchInputs = {
  q: string;
  restrict_sr: string;
  sort: string;
  t: string;
  limit: string;
};

export type RedditSearchData = {
  RESULTS: any;
  COUNT: number;
  RESULTS_SUMMARY: any[];
};
