// This file is auto-generated by scripts/generate-warp-types.js

export type PolymarketViewLatestPredictionsInputs = {
  limit: string;
};

export type PolymarketViewLatestPredictionsData = {
  ACTIVE_MARKETS: any;
  MARKET_COUNT: number;
  PREDICTIONS: any[];
};
