// This file is auto-generated by scripts/generate-warp-types.js

export type PolymarketBuySharesInputs = {
  marketId: string;
  outcome: string;
  amount: string;
  price: string;
};

export type PolymarketBuySharesData = {
  ORDER_ID: any;
};

export type PolymarketClaimWinningsInputs = {
  parentCollectionId: string;
  conditionId: string;
  indexSets: string;
};

export type PolymarketClaimWinningsData = {
  SUCCESS: any;
};

export type PolymarketCreateMarketInputs = {
  question: string;
  description: string;
  endDate: string;
  category: string;
};

export type PolymarketCreateMarketData = {
  MARKET_ID: any;
};

export type PolymarketGetActivePredictionsInputs = {
  limit: string;
};

export type PolymarketGetActivePredictionsData = {
  ACTIVE_MARKETS: any;
  MARKET_COUNT: number;
  MARKETS_SUMMARY: any[];
};

export type PolymarketGetCollectionIDInputs = {
  parentCollectionId: string;
  conditionId: string;
  indexSet: string;
};

export type PolymarketGetCollectionIDData = {
  COLLECTION_ID: any;
};

export type PolymarketGetConditionInfoInputs = {
  conditionId: string;
};

export type PolymarketGetConditionInfoData = {
  OUTCOME_SLOT_COUNT: number;
  ORACLE: any;
  QUESTION_ID: any;
  OUTCOME_SLOT_COUNT_FROM_CONDITION: any;
};

export type PolymarketGetLatestMarketsInputs = {
  limit: string;
  active: string;
};

export type PolymarketGetLatestMarketsData = {
  MARKET_COUNT: number;
  ACTIVE_MARKETS: number;
  LATEST_MARKETS: any[];
};

export type PolymarketGetPositionBalanceInputs = {
  account: string;
  positionId: string;
};

export type PolymarketGetPositionBalanceData = {
  BALANCE: any;
};

export type PolymarketGetPositionIDInputs = {
  collateralToken: string;
  collectionId: string;
};

export type PolymarketGetPositionIDData = {
  POSITION_ID: any;
};

export type PolymarketResolveMarketInputs = {
  marketId: string;
  winningOutcome: string;
};

export type PolymarketResolveMarketData = {
  RESOLVED: any;
};

export type PolymarketSellSharesInputs = {
  marketId: string;
  outcome: string;
  shares: string;
  price: string;
};

export type PolymarketSellSharesData = {
  ORDER_ID: any;
};

export type PolymarketViewLatestPredictionsInputs = {
  limit: string;
};

export type PolymarketViewLatestPredictionsData = {
  ACTIVE_MARKETS: any;
  MARKET_COUNT: number;
  PREDICTIONS: any[];
};
