// This file is auto-generated by scripts/generate-warp-types.js

export type InstagramDeleteCommentInputs = {
  COMMENT_ID: string;
};

export type InstagramDeleteCommentData = {
  SUCCESS: any;
};

export type InstagramGetMediaInputs = {
  MEDIA_ID: string;
  fields: string;
};

export type InstagramGetMediaData = {
  MEDIA_ID: any;
  CAPTION: any;
  MEDIA_TYPE: any;
  PERMALINK: any;
  LIKE_COUNT: number;
  COMMENTS_COUNT: number;
  TIMESTAMP: number;
};

export type InstagramGetProfileInputs = {
  IG_USER_ID: string;
  fields: string;
};

export type InstagramGetProfileData = {
  USERNAME: any;
  NAME: any;
  BIOGRAPHY: any;
  FOLLOWERS: any;
  FOLLOWING: any;
  MEDIA_COUNT: number;
  PROFILE_PIC: any;
};

export type InstagramHideCommentInputs = {
  COMMENT_ID: string;
  hide: string;
};

export type InstagramHideCommentData = {
  SUCCESS: any;
};

export type InstagramListMediaCommentsInputs = {
  MEDIA_ID: string;
  fields: string;
};

export type InstagramListMediaCommentsData = {
  COMMENTS: any;
};

export type InstagramListMediaInputs = {
  IG_USER_ID: string;
  fields: string;
};

export type InstagramListMediaData = {
  MEDIA: any;
};

export type InstagramReplytoCommentInputs = {
  COMMENT_ID: string;
  message: string;
};

export type InstagramReplytoCommentData = {
  REPLY_ID: any;
};

export type InstagramSendMessageInputs = {
  IG_USER_ID: string;
  RECIPIENT_ID: string;
  TEXT: string;
  recipient: string;
  message: string;
};

export type InstagramSendMessageData = {
  RECIPIENT_ID: any;
  MESSAGE_ID: any;
};

export type InstagramSendPrivateReplyInputs = {
  PAGE_ID: string;
  COMMENT_ID: string;
  MESSAGE_TEXT: string;
  recipient: string;
  message: string;
};

export type InstagramSendPrivateReplyData = {
  RECIPIENT_ID: any;
  MESSAGE_ID: any;
};
