// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXStakingClaimRewardsAllInputs = {
};

export type MultiversXStakingClaimRewardsAllData = {
  DELEGATIONS: any;
  CLAIMS: number;
  TOTAL_REWARDS_CLAIMED_EGLD: number;
  PROVIDER_COUNT: string;
};
