// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXStakingClaimRewardsAllInputs = {
};

export type MultiversXStakingClaimRewardsAllData = {
  CLAIMS: any[];
  TOTAL_REWARDS_CLAIMED_EGLD: number;
  PROVIDER_COUNT: number;
};
