// This file is auto-generated by scripts/generate-warp-types.js

export type DropboxListFolderInputs = {
  path: string;
};

export type DropboxListFolderData = {
  ENTRIES: any;
  COUNT: any;
};

export type DropboxUploadFileInputs = {
  PATH: string;
  content: string;
};

export type DropboxUploadFileData = {
  NAME: any;
  PATH: any;
};
