// This file is auto-generated by scripts/generate-warp-types.js

export type DropboxUploadFileInputs = {
  PATH: string;
  content: string;
};

export type DropboxUploadFileData = {
  NAME: any;
  PATH: any;
};
