// This file is auto-generated by scripts/generate-warp-types.js

export type TickTickCreateTaskInputs = {
  title: string;
  content: string;
};

export type TickTickCreateTaskData = {
  TASK_ID: any;
  TITLE: any;
};
