// This file is auto-generated by scripts/generate-warp-types.js

export type SendGridSendEmailInputs = {
  to: string;
  from: string;
  subject: string;
  value: string;
  type: string;
};

export type SendGridSendEmailData = {
  STATUS: string;
};
