// This file is auto-generated by scripts/generate-warp-types.js

export type JoAiListServicesInputs = {
  team: string;
};

export type JoAiListServicesData = {
  services: any;
  servicesList: any;
  servicesCount: any;
};
