// This file is auto-generated by scripts/generate-warp-types.js

export type CLICopytoClipboardInputs = {
  TEXT: string;
};

export type CLIReadClipboardInputs = {
};

export type CLICompressZIPInputs = {
  INPUT: string;
  OUTPUT: string;
};

export type CLICopyFileInputs = {
  SOURCE: string;
  DESTINATION: string;
};

export type CLICreateFolderInputs = {
  PATH: string;
};

export type CLICurrentDirectoryInputs = {
};

export type CLIDecompressZIPInputs = {
  ARCHIVE: string;
  DESTINATION: string;
};

export type CLIDeleteFileInputs = {
  PATH: string;
};

export type CLIDiskUsageInputs = {
};

export type CLIDownloadFileInputs = {
  URL: string;
  OUTPUT: string;
};

export type CLIExecuteInputs = {
  COMMAND: string;
};

export type CLIFindFilesInputs = {
  PATTERN: string;
  PATH: string;
};

export type CLIFolderSizeInputs = {
  PATH: string;
};

export type CLIListFilesInputs = {
  PATH: string;
};

export type CLIMoveFileInputs = {
  SOURCE: string;
  DESTINATION: string;
};

export type CLINetworkInfoInputs = {
};

export type CLIOpenAppInputs = {
  APP_NAME: string;
};

export type CLIOpenFileInputs = {
  FILE_PATH: string;
};

export type CLIOpenURLInputs = {
  URL: string;
};

export type CLIKillProcessInputs = {
  PID: string;
};

export type CLIProcessListInputs = {
};

export type CLIReadFileInputs = {
  FILE_PATH: string;
};

export type CLIScreenshotInputs = {
  FILE_PATH: string;
};

export type CLISearchFileContentInputs = {
  PATTERN: string;
  PATH: string;
};

export type CLISystemInfoInputs = {
};
