// This file is auto-generated by scripts/generate-warp-types.js

export type OpenCodeAddFollowupInputs = {
  RUN_ID: string;
  FOLLOWUP: string;
  PART_TYPE: string;
};

export type OpenCodeAddFollowupData = {
  RUN_ID: any;
  RUN_STATUS: string;
  SUMMARY: string;
};

export type OpenCodeCancelTaskInputs = {
  RUN_ID: string;
};

export type OpenCodeCancelTaskData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type OpenCodeGetTaskStatusInputs = {
  RUN_ID: string;
};

export type OpenCodeGetTaskStatusData = {
  RUN_ID: any;
  RUN_STATUS: string;
  RUN_URL: string;
  SUMMARY: string;
};

export type OpenCodeLaunchTaskInputs = {
  TASK: string;
};

export type OpenCodeLaunchTaskData = {
  RUN_ID: any;
  RUN_STATUS: string;
  RUN_URL: string;
  SUMMARY: string;
};
