// This file is auto-generated by scripts/generate-warp-types.js

export type ChessJoinGameInputs = {
};

export type ChessJoinGameData = {
  TX_HASH: string;
};

export type ChessMakeMoveInputs = {
};

export type ChessMakeMoveData = {
  TX_HASH: string;
};

export type ChessResignInputs = {
};

export type ChessResignData = {
  TX_HASH: string;
};
