// This file is auto-generated by scripts/generate-warp-types.js

export type FirecrawlCrawlInputs = {
  url: string;
  maxDepth: number;
  limit: number;
  includePaths: string;
  excludePaths: string;
};

export type FirecrawlCrawlData = {
  SUCCESS: any;
  JOB_ID: string;
  STATUS_URL: string;
};

export type FirecrawlMapInputs = {
  url: string;
  search: string;
  includeSubdomains: boolean;
  limit: number;
};

export type FirecrawlMapData = {
  SUCCESS: any;
  LINKS: any;
};

export type FirecrawlScrapeInputs = {
  url: string;
  waitFor: number;
  includeTags: string;
  excludeTags: string;
};

export type FirecrawlScrapeData = {
  CONTENT: any;
  MARKDOWN: any;
  HTML: any;
  METADATA: any;
  SUCCESS: any;
};

export type FirecrawlSearchInputs = {
  query: string;
  location: string;
  limit: number;
  lang: string;
};

export type FirecrawlSearchData = {
  SUCCESS: any;
  RESULTS: any;
};
