// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXIssueSemiFungibleTokenCollectionInputs = {
  COLLECTION_NAME: string;
  COLLECTION_TICKER: string;
};

export type MultiversXIssueSemiFungibleTokenCollectionData = {
  TX_HASH: string;
  COLLECTION_ID: any;
  COLLECTION_NAME: any;
  COLLECTION_TICKER: any;
};
