// This file is auto-generated by scripts/generate-warp-types.js

export type HTTPJSONPUTRequestInputs = {
  URL: string;
  PAYLOAD: string;
  HEADERS: string;
};

export type HTTPJSONPUTRequestData = {
  RESPONSE: any;
};
