// This file is auto-generated by scripts/generate-warp-types.js

export type HTTPJSONDELETERequestInputs = {
  URL: string;
  HEADERS: string;
};

export type HTTPJSONDELETERequestData = {
  RESPONSE: any;
};

export type HTTPJSONGETRequestInputs = {
  URL: string;
  QUERIES: string;
  HEADERS: string;
};

export type HTTPJSONGETRequestData = {
  RESPONSE: any;
};

export type HTTPJSONPOSTRequestInputs = {
  URL: string;
  PAYLOAD: string;
  HEADERS: string;
};

export type HTTPJSONPOSTRequestData = {
  RESPONSE: any;
};

export type HTTPJSONPUTRequestInputs = {
  URL: string;
  PAYLOAD: string;
  HEADERS: string;
};

export type HTTPJSONPUTRequestData = {
  RESPONSE: any;
};
