// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct LoyaltyContractProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for LoyaltyContractProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = LoyaltyContractProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        LoyaltyContractProxyMethods { wrapped_tx: tx }
    }
}

pub struct LoyaltyContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> LoyaltyContractProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> LoyaltyContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> LoyaltyContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn create_loyalty<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("createLoyalty")
            .argument(&slug)
            .original_result()
    }

    pub fn get_loyalty_info<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, LoyaltyInfo<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getLoyaltyInfo")
            .argument(&slug)
            .original_result()
    }

    pub fn configure_loyalty<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u32>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<u8>,
        Arg5: ProxyArg<u32>,
    >(
        self,
        slug: Arg0,
        stamps_for_reward: Arg1,
        reward_label: Arg2,
        review_url: Arg3,
        review_discount: Arg4,
        reminder_days: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("configureLoyalty")
            .argument(&slug)
            .argument(&stamps_for_reward)
            .argument(&reward_label)
            .argument(&review_url)
            .argument(&review_discount)
            .argument(&reminder_days)
            .original_result()
    }

    pub fn register<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
        card_uuid: Arg1,
        name: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("register")
            .argument(&slug)
            .argument(&card_uuid)
            .argument(&name)
            .original_result()
    }

    pub fn add_stamp<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
        card_uuid: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("addStamp")
            .argument(&slug)
            .argument(&card_uuid)
            .original_result()
    }

    pub fn redeem_reward<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
        card_uuid: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("redeemReward")
            .argument(&slug)
            .argument(&card_uuid)
            .original_result()
    }

    pub fn set_discount<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<u8>,
    >(
        self,
        slug: Arg0,
        card_uuid: Arg1,
        percent: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setDiscount")
            .argument(&slug)
            .argument(&card_uuid)
            .argument(&percent)
            .original_result()
    }

    pub fn clear_discount<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
        card_uuid: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("clearDiscount")
            .argument(&slug)
            .argument(&card_uuid)
            .original_result()
    }

    pub fn get_status<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
        card_uuid: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, CustomerStatus<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getStatus")
            .argument(&slug)
            .argument(&card_uuid)
            .original_result()
    }

    pub fn is_card_registered<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
        card_uuid: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("isCardRegistered")
            .argument(&slug)
            .argument(&card_uuid)
            .original_result()
    }

    pub fn get_loyalty_config<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, LoyaltyConfig<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getLoyaltyConfig")
            .argument(&slug)
            .original_result()
    }

    pub fn get_stale_customers<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<u32>,
    >(
        self,
        slug: Arg0,
        since_timestamp: Arg1,
        limit: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, StaleCustomer<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getStaleCustomers")
            .argument(&slug)
            .argument(&since_timestamp)
            .argument(&limit)
            .original_result()
    }

    pub fn get_customer_count<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, usize> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getCustomerCount")
            .argument(&slug)
            .original_result()
    }
}

#[type_abi]
#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode)]
pub struct LoyaltyInfo<Api>
where
    Api: ManagedTypeApi,
{
    pub owner: ManagedAddress<Api>,
    pub created_at: u64,
}

#[type_abi]
#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode)]
pub struct CustomerStatus<Api>
where
    Api: ManagedTypeApi,
{
    pub name: ManagedBuffer<Api>,
    pub stamps: u32,
    pub stamps_for_reward: u32,
    pub discount: u8,
    pub reward_ready: bool,
    pub last_visit: u64,
}

#[type_abi]
#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode)]
pub struct LoyaltyConfig<Api>
where
    Api: ManagedTypeApi,
{
    pub stamps_for_reward: u32,
    pub reward_label: ManagedBuffer<Api>,
    pub review_url: ManagedBuffer<Api>,
    pub review_discount: u8,
    pub reminder_days: u32,
}

#[type_abi]
#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode)]
pub struct StaleCustomer<Api>
where
    Api: ManagedTypeApi,
{
    pub customer_id: u64,
    pub card_uuid: ManagedBuffer<Api>,
    pub last_visit: u64,
}
