// This file is auto-generated by scripts/generate-warp-types.js

export type SuiGetSystemStateInputs = {
};

export type SuiGetSystemStateData = {
  SYSTEM_STATE: any;
  SYSTEM_TYPE: string;
  SYSTEM_VERSION: string;
};
