// This file is auto-generated by scripts/generate-warp-types.js

export type SuiGetBalanceInputs = {
  COIN_OBJECT_ID: string;
};

export type SuiGetBalanceData = {
  BALANCE: string;
  BALANCE_SUI: number;
};

export type SuiGetObjectInputs = {
  OBJECT_ID: string;
};

export type SuiGetObjectData = {
  OBJECT_DATA: any;
  _DATA: any;
  OBJECT_TYPE: string;
  OBJECT_OWNER: string;
  OBJECT_VERSION: string;
};

export type SuiGetStakesInputs = {
  STAKED_SUI_ID: string;
};

export type SuiGetStakesData = {
  STAKE_DATA: any;
  _DATA: any;
  STAKE_TYPE: string;
  PRINCIPAL: string;
  PRINCIPAL_SUI: number;
};

export type SuiGetSystemStateInputs = {
};

export type SuiGetSystemStateData = {
  SYSTEM_STATE: any;
  SYSTEM_TYPE: string;
  SYSTEM_VERSION: string;
};
