// This file is auto-generated by scripts/generate-warp-types.js

export type HubSpotCreateContactInputs = {
  email: string;
  firstname: string;
  lastname: string;
};

export type HubSpotCreateContactData = {
  CONTACT_ID: any;
  EMAIL: any;
  FIRST_NAME: any;
  LAST_NAME: any;
};

export type HubSpotGetContactInputs = {
  CONTACT_ID: string;
  properties: string;
};

export type HubSpotGetContactData = {
  CONTACT_ID: any;
  EMAIL: any;
  FIRST_NAME: any;
  LAST_NAME: any;
};
