// This file is auto-generated by scripts/generate-warp-types.js

export type HubSpotGetContactInputs = {
  CONTACT_ID: string;
  properties: string;
};

export type HubSpotGetContactData = {
  CONTACT_ID: any;
  EMAIL: any;
  FIRST_NAME: any;
  LAST_NAME: any;
};
