// This file is auto-generated by scripts/generate-warp-types.js

export type YouTubeGetVideoInputs = {
  VIDEO_ID: string;
  PART: string;
};

export type YouTubeGetVideoData = {
  TITLE: any;
  CHANNEL: any;
  VIEWS: any;
  LIKES: any;
  COMMENTS: any;
  DESCRIPTION: any;
  PUBLISHED_AT: any;
};

export type YouTubeListChannelVideosInputs = {
  CHANNEL_ID: string;
  ORDER: string;
  MAX_RESULTS: number;
};

export type YouTubeListChannelVideosData = {
  VIDEOS: any;
  COUNT: any;
};

export type YouTubeSearchInputs = {
  QUERY: string;
  PART: string;
  TYPE: string;
  MAX_RESULTS: number;
};

export type YouTubeSearchData = {
  ITEMS: any;
  COUNT: any;
};
