// This file is auto-generated by scripts/generate-warp-types.js

export type YouTubeSearchInputs = {
  key: string;
  q: string;
  part: string;
  type: string;
  maxResults: number;
};

export type YouTubeSearchData = {
  ITEMS: any;
  COUNT: any;
};
