// This file is auto-generated by scripts/generate-warp-types.js

export type LinearUpdateIssueInputs = {
  issueId: string;
  title: string;
  description: string;
  stateId: string;
  assigneeId: string;
  priority: number;
  query: string;
};

export type LinearUpdateIssueData = {
  ISSUE_ID: any;
  IDENTIFIER: any;
  TITLE: any;
  URL: any;
  STATE: any;
  SUCCESS: any;
};
