// This file is auto-generated by scripts/generate-warp-types.js

export type LinearAddCommentInputs = {
  issueId: string;
  body: string;
  query: string;
};

export type LinearAddCommentData = {
  COMMENT_ID: any;
  COMMENT_BODY: any;
  AUTHOR: any;
  CREATED_AT: any;
  SUCCESS: any;
};

export type LinearCreateIssueInputs = {
  teamId: string;
  title: string;
  description: string;
  assigneeId: string;
  priority: number;
  query: string;
};

export type LinearCreateIssueData = {
  ISSUE_ID: any;
  ISSUE_TITLE: any;
  ISSUE_URL: any;
  ISSUE_IDENTIFIER: any;
  SUCCESS: any;
};

export type LinearGetIssueInputs = {
  issueId: string;
  query: string;
};

export type LinearGetIssueData = {
  ISSUE_ID: any;
  IDENTIFIER: any;
  TITLE: any;
  DESCRIPTION: any;
  STATE: any;
  ASSIGNEE: any;
  PRIORITY: any;
  URL: any;
  CREATED_AT: any;
};

export type LinearListIssuesInputs = {
  teamId: string;
  assigneeId: string;
  state: string;
  first: number;
  query: string;
};

export type LinearListIssuesData = {
  ISSUES: any;
  COUNT: number;
};

export type LinearListTeamsInputs = {
  query: string;
};

export type LinearListTeamsData = {
  TEAMS: any;
  COUNT: number;
};

export type LinearUpdateIssueInputs = {
  issueId: string;
  title: string;
  description: string;
  stateId: string;
  assigneeId: string;
  priority: number;
  query: string;
};

export type LinearUpdateIssueData = {
  ISSUE_ID: any;
  IDENTIFIER: any;
  TITLE: any;
  URL: any;
  STATE: any;
  SUCCESS: any;
};
