// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXStakingViewDelegationsInputs = {
  ACCOUNT: string;
};

export type MultiversXStakingViewDelegationsData = {
  TOTAL_STAKED: number;
  TOTAL_STAKED_EGLD: number;
  TOTAL_REWARDS: number;
  TOTAL_REWARDS_EGLD: number;
  PROVIDER_COUNT: number;
};
