// This file is auto-generated by scripts/generate-warp-types.js

export type NotionSearchInputs = {
  query: string;
  direction: string;
  timestamp: string;
};

export type NotionSearchData = {
  RESULTS: any;
  COUNT: any;
};
