// This file is auto-generated by scripts/generate-warp-types.js

export type NotionAppendBlockInputs = {
  BLOCK_ID: string;
  children: string;
};

export type NotionAppendBlockData = {
  RESULTS: any;
  COUNT: any;
};

export type NotionCreatePageInputs = {
  databaseId: string;
  pageId: string;
  title: string;
};

export type NotionCreatePageData = {
  PAGE_ID: any;
  URL: any;
};

export type NotionGetBlockChildrenInputs = {
  BLOCK_ID: string;
  page_size: number;
};

export type NotionGetBlockChildrenData = {
  BLOCKS: any;
  COUNT: any;
  HAS_MORE: boolean;
};

export type NotionGetPageInputs = {
  PAGE_ID: string;
};

export type NotionGetPageData = {
  PAGE_ID: any;
  URL: any;
  PROPERTIES: any;
  CREATED_TIME: any;
  LAST_EDITED_TIME: any;
};

export type NotionQueryDatabaseInputs = {
  DATABASE_ID: string;
  filter: string;
  page_size: number;
};

export type NotionQueryDatabaseData = {
  RESULTS: any;
  COUNT: any;
  HAS_MORE: boolean;
  NEXT_CURSOR: any;
};

export type NotionSearchInputs = {
  query: string;
  direction: string;
  timestamp: string;
};

export type NotionSearchData = {
  RESULTS: any;
  COUNT: any;
};

export type NotionUpdatePageInputs = {
  PAGE_ID: string;
  properties: string;
};

export type NotionUpdatePageData = {
  PAGE_ID: any;
  URL: any;
  LAST_EDITED_TIME: any;
};
