// This file is auto-generated by scripts/generate-warp-types.js

export type gameguessnumbercheckInputs = {
};

export type gameguessnumberstartInputs = {
};

export type gameguessnumberstopInputs = {
};
