// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleSheetsGetValuesInputs = {
  SPREADSHEET_ID: string;
  RANGE: string;
};

export type GoogleSheetsGetValuesData = {
  VALUES: any;
};
