// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleSheetsAddSheetInputs = {
  SPREADSHEET_ID: string;
  SHEET_TITLE: string;
  requests: string;
};

export type GoogleSheetsAddSheetData = {
  SHEET_ID: any;
  SHEET_TITLE: any;
};

export type GoogleSheetsAppendValuesInputs = {
  SPREADSHEET_ID: string;
  RANGE: string;
  values: string;
  valueInputOption: string;
};

export type GoogleSheetsAppendValuesData = {
  UPDATED_RANGE: any;
  UPDATED_ROWS: any;
};

export type GoogleSheetsBatchGetValuesInputs = {
  SPREADSHEET_ID: string;
  ranges: string;
};

export type GoogleSheetsBatchGetValuesData = {
  VALUE_RANGES: any;
};

export type GoogleSheetsBatchUpdateValuesInputs = {
  SPREADSHEET_ID: string;
  data: string;
  valueInputOption: string;
};

export type GoogleSheetsBatchUpdateValuesData = {
  UPDATED_ROWS: any;
  UPDATED_CELLS: any;
  UPDATED_SHEETS: any;
};

export type GoogleSheetsClearValuesInputs = {
  SPREADSHEET_ID: string;
  RANGE: string;
};

export type GoogleSheetsClearValuesData = {
  CLEARED_RANGE: any;
};

export type GoogleSheetsCopySheetInputs = {
  SPREADSHEET_ID: string;
  SHEET_ID: number;
  destinationSpreadsheetId: string;
};

export type GoogleSheetsCopySheetData = {
  NEW_SHEET_ID: any;
  NEW_SHEET_TITLE: any;
};

export type GoogleSheetsCreateSpreadsheetInputs = {
  title: string;
};

export type GoogleSheetsCreateSpreadsheetData = {
  SPREADSHEET_ID: any;
  SPREADSHEET_URL: any;
};

export type GoogleSheetsDeleteSheetInputs = {
  SPREADSHEET_ID: string;
  SHEET_ID: number;
  requests: string;
};

export type GoogleSheetsFindandReplaceInputs = {
  SPREADSHEET_ID: string;
  FIND_TEXT: string;
  REPLACE_TEXT: string;
  MATCH_CASE: string;
  requests: string;
};

export type GoogleSheetsFindandReplaceData = {
  OCCURRENCES: any;
  ROWS_CHANGED: any;
  SHEETS_CHANGED: any;
};

export type GoogleSheetsGetSpreadsheetInputs = {
  SPREADSHEET_ID: string;
};

export type GoogleSheetsGetSpreadsheetData = {
  TITLE: any;
  LOCALE: any;
  SPREADSHEET_URL: any;
  SHEETS: any;
};

export type GoogleSheetsGetValuesInputs = {
  SPREADSHEET_ID: string;
  RANGE: string;
};

export type GoogleSheetsGetValuesData = {
  VALUES: any;
};

export type GoogleSheetsUpdateValuesInputs = {
  SPREADSHEET_ID: string;
  RANGE: string;
  values: string;
  valueInputOption: string;
};

export type GoogleSheetsUpdateValuesData = {
  UPDATED_RANGE: any;
  UPDATED_ROWS: any;
  UPDATED_CELLS: any;
};
