// This file is auto-generated by scripts/generate-warp-types.js

export type ChallengeAcceptInputs = {
  stake: string;
  challengeId: string;
};

export type ChallengeCreateInputs = {
  stake: string;
  title: string;
  durationHours: string;
};

export type ChallengeCreateData = {
  CHALLENGE_ID: any;
};

export type ChallengeBrowseInputs = {
};

export type ChallengeBrowseData = {
  CHALLENGES: any;
};

export type ChallengeResolveInputs = {
  challengeId: string;
  creatorSucceeded: string;
};

export type ChallengeViewInputs = {
  challengeId: string;
};

export type ChallengeViewData = {
  CREATOR: any;
  TITLE: any;
  STAKE: any;
  ENDS_AT: any;
  STATUS: string;
  ACCEPTOR: any;
};
