// This file is auto-generated by scripts/generate-warp-types.js

export type RunningCoachLogRunInputs = {
  distance: number;
  duration: number;
  effort: string;
  notes: string;
};

export type RunningCoachOnboardInputs = {
  goal: string;
  currentDistance: number;
  currentPace: number;
  daysPerWeek: number;
  raceDate: string;
};
