// This file is auto-generated by scripts/generate-warp-types.js

export type ClickUpGetTasksInputs = {
  LIST_ID: string;
  archived: boolean;
};

export type ClickUpGetTasksData = {
  TASKS: any;
  COUNT: any;
};
