// This file is auto-generated by scripts/generate-warp-types.js

export type ClickUpCreateTaskInputs = {
  LIST_ID: string;
  name: string;
  description: string;
  priority: number;
};

export type ClickUpCreateTaskData = {
  TASK_ID: any;
  TASK_NAME: any;
  URL: any;
};

export type ClickUpGetTasksInputs = {
  LIST_ID: string;
  archived: boolean;
};

export type ClickUpGetTasksData = {
  TASKS: any;
  COUNT: any;
};
