// This file is auto-generated by scripts/generate-warp-types.js

export type SpotifySearchInputs = {
  q: string;
  type: string;
  limit: number;
};

export type SpotifySearchData = {
  TRACKS: any;
  ARTISTS: any;
  ALBUMS: any;
};
