// This file is auto-generated by scripts/generate-warp-types.js

export type SpotifyGetAlbumInputs = {
  ID: string;
};

export type SpotifyGetAlbumData = {
  NAME: any;
  ARTIST: any;
  TOTAL_TRACKS: any;
  RELEASE_DATE: any;
  URL: any;
  TRACKS: any;
};

export type SpotifyGetArtistTopTracksInputs = {
  ID: string;
  market: string;
};

export type SpotifyGetArtistTopTracksData = {
  TRACKS: any;
  COUNT: any;
};

export type SpotifyGetArtistInputs = {
  ID: string;
};

export type SpotifyGetArtistData = {
  NAME: any;
  GENRES: any;
  FOLLOWERS: any;
  POPULARITY: any;
  URL: any;
  IMAGE: any;
};

export type SpotifyGetCurrentlyPlayingInputs = {
};

export type SpotifyGetCurrentlyPlayingData = {
  IS_PLAYING: boolean;
  TRACK_NAME: any;
  ARTIST: any;
  ALBUM: any;
  URL: any;
  PROGRESS_MS: any;
};

export type SpotifyGetPlaylistInputs = {
  ID: string;
};

export type SpotifyGetPlaylistData = {
  NAME: any;
  DESCRIPTION: any;
  OWNER: any;
  TOTAL_TRACKS: any;
  URL: any;
  TRACKS: any;
};

export type SpotifyGetTrackInputs = {
  ID: string;
};

export type SpotifyGetTrackData = {
  NAME: any;
  ARTIST: any;
  ALBUM: any;
  URL: any;
  PREVIEW: any;
};

export type SpotifySearchInputs = {
  q: string;
  type: string;
  limit: number;
};

export type SpotifySearchData = {
  TRACKS: any;
  ARTISTS: any;
  ALBUMS: any;
};
