// This file is auto-generated by scripts/generate-warp-types.js

export type OOXAcceptOfferInputs = {
};

export type OOXCreateAuctionInputs = {
};

export type OOXPlaceBidInputs = {
};

export type OOXBuyNowInputs = {
};

export type OOXClaimTokensInputs = {
};

export type OOXCreateVendingMachineInputs = {
};

export type OOXEndAuctionInputs = {
};

export type OOXGetAuctionDataInputs = {
};

export type OOXGetOfferDataInputs = {
};

export type OOXMintfromVendingMachineInputs = {
};

export type OOXModifyAuctionPriceInputs = {
};

export type OOXSendOfferInputs = {
};

export type OOXWithdrawfromAuctionInputs = {
};

export type OOXWithdrawOfferInputs = {
};
