// This file is auto-generated by scripts/generate-warp-types.js

export type BlueskyCreatePostInputs = {
  repo: string;
  text: string;
  collection: string;
  $type: string;
  createdAt: string;
};

export type BlueskyCreatePostData = {
  URI: any;
  CID: any;
};

export type BlueskyGetAuthorFeedInputs = {
  actor: string;
  limit: string;
};

export type BlueskyGetAuthorFeedData = {
  FEED: any;
  CURSOR: any;
};

export type BlueskyGetProfileInputs = {
  actor: string;
};

export type BlueskyGetProfileData = {
  HANDLE: any;
  DISPLAY_NAME: any;
  FOLLOWERS: any;
  FOLLOWING: any;
  POSTS: any;
};
