// This file is auto-generated by scripts/generate-warp-types.js

export type CouponCreateInputs = {
  code: string;
  discountPercent: string;
  maxUses: string;
  expiryDays: string;
};

export type CouponMyCouponsInputs = {
  owner: string;
};

export type CouponMyCouponsData = {
  COUPONS: any;
};

export type CouponRedeemInputs = {
  code: string;
};

export type CouponRedeemData = {
  DISCOUNT: any;
};

export type CouponRevokeInputs = {
  code: string;
};

export type CouponViewInputs = {
  code: string;
};

export type CouponViewData = {
  DISCOUNT: any;
  MAX_USES: any;
  USED_COUNT: number;
  EXPIRES_AT: any;
  CREATED_AT: any;
  IS_REVOKED: boolean;
  OWNER: any;
};
