// This file is auto-generated by scripts/generate-warp-types.js

export type ZendeskListTicketsInputs = {
  AUTH_HEADER: string;
  page: number;
  per_page: number;
};

export type ZendeskListTicketsData = {
  TICKETS: any;
  COUNT: any;
};
