// This file is auto-generated by scripts/generate-warp-types.js

export type ZendeskCreateTicketInputs = {
  subject: string;
  body: string;
  priority: string;
};

export type ZendeskCreateTicketData = {
  TICKET_ID: any;
  SUBJECT: any;
};

export type ZendeskListTicketsInputs = {
  PAGE: number;
  PER_PAGE: number;
};

export type ZendeskListTicketsData = {
  TICKETS: any;
  COUNT: any;
};
