// This file is auto-generated by scripts/generate-warp-types.js

export type ShopifyCreateOrderInputs = {
  lineItems: string;
  email: string;
  shippingAddress: string;
  billingAddress: string;
  financialStatus: string;
  query: string;
};

export type ShopifyCreateOrderData = {
  ORDER_ID: any;
  ORDER_NAME: any;
  ORDER_TOTAL: any;
  SUCCESS: any;
};

export type ShopifyCreateProductInputs = {
  title: string;
  description: string;
  vendor: string;
  productType: string;
  tags: string;
  price: string;
  sku: string;
  inventoryQuantity: number;
  query: string;
};

export type ShopifyCreateProductData = {
  PRODUCT_ID: any;
  PRODUCT_TITLE: any;
  PRODUCT_HANDLE: any;
  SUCCESS: any;
};

export type ShopifyGetOrderInputs = {
  orderId: string;
  graphqlQuery: string;
};

export type ShopifyGetOrderData = {
  ORDER_ID: any;
  ORDER_NAME: any;
  ORDER_EMAIL: any;
  ORDER_TOTAL: any;
  ORDER_STATUS: any;
  ORDER_LINE_ITEMS: any;
};

export type ShopifyListOrdersInputs = {
  query: string;
  first: number;
  after: string;
  graphqlQuery: string;
};

export type ShopifyListOrdersData = {
  ORDERS: any;
  ORDER_COUNT: number;
  HAS_NEXT_PAGE: boolean;
};

export type ShopifyListProductsInputs = {
  query: string;
  first: number;
  after: string;
  graphqlQuery: string;
};

export type ShopifyListProductsData = {
  PRODUCTS: any;
  PRODUCT_COUNT: number;
  HAS_NEXT_PAGE: boolean;
};

export type ShopifyUpdateProductInputs = {
  productId: string;
  title: string;
  description: string;
  vendor: string;
  productType: string;
  tags: string;
  query: string;
};

export type ShopifyUpdateProductData = {
  PRODUCT_ID: any;
  PRODUCT_TITLE: any;
  SUCCESS: any;
};
