// This file is auto-generated by scripts/generate-warp-types.js

export type ShopifyUpdateProductInputs = {
  productId: string;
  title: string;
  description: string;
  vendor: string;
  productType: string;
  tags: string;
  query: string;
};

export type ShopifyUpdateProductData = {
  PRODUCT_ID: any;
  PRODUCT_TITLE: any;
  SUCCESS: any;
};
