// This file is auto-generated by scripts/generate-warp-types.js

export type ColombiaStakingUserStakeCalculationInputs = {
};

export type ColombiaStakingUserStakeCalculationData = {
  DELEGATORS: string[];
  STAKERS: any[];
};

export type ColombiaStakingBuybackwithWalletEGLDInputs = {
  ADDRESS: string;
};

export type ColombiaStakingBuybackwithWalletEGLDData = {
  BALANCE: string;
  BALANCE_EGLD: number;
};

export type ColombiaStakingBuybackInputs = {
  amount: string;
};

export type ColombiaStakingBuybackData = {
  BOUGHT_AMOUNT: number;
};

export type ColombiaStakingBuybackwithEGLDInputs = {
  amount: string;
};

export type ColombiaStakingBuybackwithEGLDData = {
  WEGLD_AMOUNT: number;
};
