// This file is auto-generated by scripts/generate-warp-types.js

export type SentryGetIssueInputs = {
  ISSUE_ID: string;
};

export type SentryGetIssueData = {
  ID: any;
  TITLE: any;
  STATUS: string;
  LEVEL: any;
  COUNT: any;
  FIRST_SEEN: any;
  LAST_SEEN: any;
};

export type SentryListEventsInputs = {
  ISSUE_ID: string;
};

export type SentryListEventsData = {
  EVENTS: any;
  COUNT: any;
};

export type SentryListIssuesInputs = {
  ORG_SLUG: string;
  PROJECT_SLUG: string;
  query: string;
};

export type SentryListIssuesData = {
  ISSUES: any;
  COUNT: any;
};

export type SentryListProjectsInputs = {
  ORG_SLUG: string;
};

export type SentryListProjectsData = {
  PROJECTS: any;
  COUNT: any;
};

export type SentryResolveIssueInputs = {
  ISSUE_ID: string;
  status: string;
};

export type SentryResolveIssueData = {
  ID: any;
  STATUS: string;
};
