// This file is auto-generated by scripts/generate-warp-types.js

export type CouponCreateCollectionInputs = {
  name: string;
  ticker: string;
};

export type CouponCreateCollectionData = {
  COLLECTION_ID: any;
};
