// This file is auto-generated by scripts/generate-warp-types.js

export type CouponMyCouponsInputs = {
  owner: string;
  offset: string;
  limit: string;
};

export type CouponMyCouponsData = {
  COUPONS: any;
};
