// This file is auto-generated by scripts/generate-warp-types.js

export type DeepBookGetPoolInfoInputs = {
  POOL_OBJECT_ID: string;
};

export type DeepBookGetPoolInfoData = {
  POOL_DATA: any;
  _DATA: any;
  POOL_TYPE: string;
  POOL_ID: string;
};
