// This file is auto-generated by scripts/generate-warp-types.js

export type AppleListiMessageChatsInputs = {
  LIMIT: string;
};

export type AppleReadiMessagesInputs = {
  CONTACT: string;
  LIMIT: string;
};

export type AppleSendiMessageInputs = {
  RECIPIENT: string;
  MESSAGE: string;
};

export type AppleOpenSettingsInputs = {
  PANE: string;
};
