// This file is auto-generated by scripts/generate-warp-types.js

export type AppleListiMessageChatsInputs = {
  limit: string;
};

export type AppleReadiMessagesInputs = {
  contact: string;
  limit: string;
};

export type AppleSendiMessageInputs = {
  recipient: string;
  message: string;
};

export type AppleOpenSettingsInputs = {
  PANE: string;
};
