// This file is auto-generated by scripts/generate-warp-types.js

export type JotFormGetFormsInputs = {
  limit: number;
  offset: number;
};

export type JotFormGetFormsData = {
  FORMS: any;
  COUNT: any;
};

export type JotFormGetSubmissionsInputs = {
  FORM_ID: string;
  limit: number;
};

export type JotFormGetSubmissionsData = {
  SUBMISSIONS: any;
  COUNT: any;
};
