// This file is auto-generated by scripts/generate-warp-types.js

export type ZohoCRMCreateLeadInputs = {
  Last_Name: string;
  Company: string;
  Email: string;
};

export type ZohoCRMCreateLeadData = {
  LEAD_ID: any;
  STATUS: string;
};

export type ZohoCRMGetRecordsInputs = {
  MODULE: string;
  page: number;
  per_page: number;
};

export type ZohoCRMGetRecordsData = {
  RECORDS: any;
  COUNT: any;
};
