// This file is auto-generated by scripts/generate-warp-types.js

export type ZohoCRMGetRecordsInputs = {
  MODULE: string;
  page: number;
  per_page: number;
};

export type ZohoCRMGetRecordsData = {
  RECORDS: any;
  COUNT: any;
};
