// This file is auto-generated by scripts/generate-warp-types.js

export type CalendarCreateEventInputs = {
  title: string;
  description: string;
  startAt: string;
  endAt: string;
  timezone: string;
  location: string;
  allDay: boolean;
};

export type CalendarCreateEventData = {
  EVENT_ID: any;
  EVENT_EXTERNAL_ID: any;
  EVENT_TITLE: any;
  EVENT_START: any;
};

export type CalendarDeleteEventInputs = {
  externalId: string;
};

export type CalendarDeleteEventData = {
  EVENT_EXTERNAL_ID: any;
  DELETED: any;
};

export type CalendarListEventsInputs = {
  from: string;
  to: string;
};

export type CalendarListEventsData = {
  CONNECTED: any;
  PROVIDER: any;
  USER_TIMEZONE: any;
  EVENTS: any;
};

export type CalendarUpdateEventInputs = {
  externalId: string;
  title: string;
  description: string;
  startAt: string;
  endAt: string;
  timezone: string;
  location: string;
  allDay: boolean;
};

export type CalendarUpdateEventData = {
  EVENT_ID: any;
  EVENT_EXTERNAL_ID: any;
  EVENT_TITLE: any;
  EVENT_START: any;
};
