// This file is auto-generated by scripts/generate-warp-types.js

export type ActiveCampaignCreateContactInputs = {
  email: string;
  firstName: string;
  lastName: string;
};

export type ActiveCampaignCreateContactData = {
  CONTACT_ID: any;
  EMAIL: any;
};

export type ActiveCampaignListContactsInputs = {
  limit: number;
  search: string;
};

export type ActiveCampaignListContactsData = {
  CONTACTS: any;
  COUNT: any;
};
