// This file is auto-generated by scripts/generate-warp-types.js

export type ActiveCampaignListContactsInputs = {
  limit: number;
  search: string;
};

export type ActiveCampaignListContactsData = {
  CONTACTS: any;
  COUNT: any;
};
