// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback:                       1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    coupon
    (
        init => init
        upgrade => upgrade
        createCollection => create_collection
        createCoupon => create_coupon
        redeemCoupon => redeem_coupon
        revokeCoupon => revoke_coupon
        getCollection => get_collection
        getCouponData => get_coupon_data
        getCollectionsByCreator => get_collections_by_creator
        getCollectionToken => get_collection_token
        isCollectionReady => is_collection_ready
        getNextCollectionId => get_next_collection_id
    )
}

multiversx_sc_wasm_adapter::async_callback! { coupon }
