// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    coupon
    (
        init => init
        upgrade => upgrade
        createCoupon => create_coupon
        redeemCoupon => redeem_coupon
        revokeCoupon => revoke_coupon
        getCoupon => get_coupon
        getOwnerCoupons => get_owner_coupons
        couponExists => coupon_exists
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
