// This file is auto-generated by scripts/generate-warp-types.js

export type CertificateClaimInputs = {
  certId: string;
};

export type CertificateCreateCollectionInputs = {
  name: string;
  ticker: string;
};

export type CertificateIssueInputs = {
  collectionId: string;
  companyName: string;
  pdfHash: string;
  document: string;
  expiresAt: string;
  recipientEmail: string;
};

export type CertificateIssueData = {
  CERT_ID: any;
};

export type CertificateRevokeInputs = {
  certId: string;
};
