// This file is auto-generated by scripts/generate-warp-types.js

export type NFCWriteInputs = {
  url: string;
  title: string;
};

export type NFCWriteData = {
  SHORT_URL: any;
  SLUG: any;
  nfc: any;
};
