// This file is auto-generated by scripts/generate-warp-types.js

export type SalesforceCreateLeadInputs = {
  LastName: string;
  Company: string;
  FirstName: string;
  Email: string;
};

export type SalesforceCreateLeadData = {
  LEAD_ID: any;
  SUCCESS: any;
};

export type SalesforceRunQueryInputs = {
  q: string;
};

export type SalesforceRunQueryData = {
  RECORDS: any;
  TOTAL_SIZE: any;
};
