// This file is auto-generated by scripts/generate-warp-types.js

export type SalesforceRunQueryInputs = {
  q: string;
};

export type SalesforceRunQueryData = {
  RECORDS: any;
  TOTAL_SIZE: any;
};
