// This file is auto-generated by scripts/generate-warp-types.js

export type AppointmentsAvailabilityInputs = {
  title: string;
  windowStart: string;
  windowEnd: string;
  durationMinutes: number;
  attendeeName: string;
  attendeeEmail: string;
  description: string;
  timezone: string;
};

export type AppointmentsAvailabilityData = {
  CONNECTED: any;
  TIMEZONE: any;
  SERVICE: any;
  SLOTS: any;
  SLOT_COUNT: number;
};

export type AppointmentsBookInputs = {
  title: string;
  scheduledAt: string;
  timezone: string;
  serviceSlug: string;
  routedAgentUuid: string;
  appointmentRequestId: string;
  attendeeName: string;
  attendeeEmail: string;
  description: string;
  conferenceProvider: string;
};

export type AppointmentsBookData = {
  MEETING_ID: any;
  MEETING_URL: any;
  ATTENDEE_EMAIL: any;
  ATTENDEE_NAME: any;
  MEETING_TITLE: any;
  SCHEDULED_AT: any;
};

export type AppointmentsCancelPublicInputs = {
  meetingId: string;
  reason: string;
};

export type AppointmentsCancelPublicData = {
  MEETING_ID: any;
  STATUS: string;
  MEETING_TITLE: any;
};

export type AppointmentsCancelInputs = {
  meetingId: string;
  reason: string;
};

export type AppointmentsCancelData = {
  MEETING_ID: any;
  STATUS: string;
  MEETING_TITLE: any;
};

export type AppointmentsSendConfirmationEmailInputs = {
  ATTENDEE_EMAIL: string;
  ATTENDEE_NAME: string;
  MEETING_TITLE: string;
  SCHEDULED_AT: string;
  MEETING_URL: string;
  INTEGRATION: string;
  RECIPIENT_ID: string;
  RECIPIENT_NAME: string;
  MESSAGE: string;
};

export type AppointmentsSendConfirmationEmailData = {
  EMAIL_ROOM_ID: any;
};

export type AppointmentsOnboardingInputs = {
};

export type AppointmentsUpsertPolicyInputs = {
  policy: string;
};

export type AppointmentsCreateRequestInputs = {
  title: string;
  serviceSlug: string;
  requesterName: string;
  requesterEmail: string;
  windowStart: string;
  durationMinutes: number;
  timezone: string;
  failureReason: string;
  notes: string;
};

export type AppointmentsRescheduleInputs = {
  meetingId: string;
  scheduledAt: string;
  timezone: string;
};

export type AppointmentsRescheduleData = {
  MEETING_ID: any;
  SCHEDULED_AT: any;
};
