// This file is auto-generated by scripts/generate-warp-types.js

export type AirtableListRecordsInputs = {
  BASE_ID: string;
  TABLE_ID: string;
  maxRecords: number;
};

export type AirtableListRecordsData = {
  RECORDS: any;
  COUNT: any;
};
