// This file is auto-generated by scripts/generate-warp-types.js

export type AirtableCreateFieldInputs = {
  BASE_ID: string;
  TABLE_ID: string;
  name: string;
  type: string;
  description: string;
  options: string;
};

export type AirtableCreateFieldData = {
  FIELD_ID: any;
  FIELD_NAME: any;
  FIELD_TYPE: any;
};

export type AirtableCreateRecordInputs = {
  BASE_ID: string;
  TABLE_ID: string;
  fields: string;
};

export type AirtableCreateRecordData = {
  RECORD_ID: any;
  CREATED_TIME: any;
};

export type AirtableCreateTableInputs = {
  BASE_ID: string;
  name: string;
  description: string;
  fields: string;
};

export type AirtableCreateTableData = {
  TABLE_ID: any;
  TABLE_NAME: any;
};

export type AirtableDeleteRecordInputs = {
  BASE_ID: string;
  TABLE_ID: string;
  RECORD_ID: string;
};

export type AirtableDeleteRecordData = {
  DELETED: any;
  RECORD_ID: any;
};

export type AirtableGetBaseSchemaInputs = {
  BASE_ID: string;
};

export type AirtableGetBaseSchemaData = {
  TABLES: any;
  TABLE_COUNT: number;
};

export type AirtableGetRecordInputs = {
  BASE_ID: string;
  TABLE_ID: string;
  RECORD_ID: string;
};

export type AirtableGetRecordData = {
  RECORD_ID: any;
  FIELDS: any;
  CREATED_TIME: any;
};

export type AirtableListBasesInputs = {
};

export type AirtableListBasesData = {
  BASES: any;
  COUNT: number;
};

export type AirtableListRecordsInputs = {
  BASE_ID: string;
  TABLE_ID: string;
  maxRecords: number;
};

export type AirtableListRecordsData = {
  RECORDS: any;
  COUNT: any;
};

export type AirtableUpdateRecordInputs = {
  BASE_ID: string;
  TABLE_ID: string;
  RECORD_ID: string;
  fields: string;
};

export type AirtableUpdateRecordData = {
  RECORD_ID: any;
  FIELDS: any;
};

export type AirtableUpdateTableInputs = {
  BASE_ID: string;
  TABLE_ID: string;
  name: string;
  description: string;
};

export type AirtableUpdateTableData = {
  TABLE_ID: any;
  TABLE_NAME: any;
};
