// This file is auto-generated by scripts/generate-warp-types.js

export type GumroadGetProductInputs = {
  PRODUCT_ID: string;
  access_token: string;
};

export type GumroadGetProductData = {
  PRODUCT: any;
  NAME: any;
  SALES_COUNT: number;
  REVENUE: any;
};

export type GumroadListProductsInputs = {
  access_token: string;
};

export type GumroadListProductsData = {
  PRODUCTS: any;
  COUNT: any;
};

export type GumroadListSalesInputs = {
  access_token: string;
  after: string;
  before: string;
  product_id: string;
  email: string;
  page: string;
};

export type GumroadListSalesData = {
  SALES: any;
  COUNT: any;
};

export type GumroadListSubscribersInputs = {
  PRODUCT_ID: string;
  access_token: string;
};

export type GumroadListSubscribersData = {
  SUBSCRIBERS: any;
  COUNT: any;
};
