// This file is auto-generated by scripts/generate-warp-types.js

export type SocialCritiqueRefineInputs = {
  CONTENT: string;
  STYLE_INSTRUCTIONS: string;
};

export type SocialExpandInputs = {
  CONTENT: string;
  STYLE_INSTRUCTIONS: string;
};

export type SocialMakePunchierInputs = {
  CONTENT: string;
  STYLE_INSTRUCTIONS: string;
};

export type SocialMakeShorterInputs = {
  CONTENT: string;
  STYLE_INSTRUCTIONS: string;
};

export type SocialMatchVoiceInputs = {
  CONTENT: string;
  STYLE_INSTRUCTIONS: string;
};

export type SocialOptimizeHookInputs = {
  CONTENT: string;
  STYLE_INSTRUCTIONS: string;
};

export type SocialWriteVariationsInputs = {
  CONTENT: string;
  STYLE_INSTRUCTIONS: string;
};
