// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleSlidesCreatePresentationInputs = {
  title: string;
};

export type GoogleSlidesCreatePresentationData = {
  PRESENTATION_ID: any;
  TITLE: any;
};
