// This file is auto-generated by scripts/generate-warp-types.js

export type GmailGetMessageInputs = {
  MESSAGE_ID: string;
  format: string;
};

export type GmailGetMessageData = {
  MESSAGE_ID: any;
  THREAD_ID: any;
  SNIPPET: any;
  HEADERS: any;
  LABELS: any;
  BODY: any;
};

export type GmailGetThreadInputs = {
  THREAD_ID: string;
};

export type GmailGetThreadData = {
  THREAD_ID: any;
  MESSAGES: any;
  MESSAGE_COUNT: number;
};

export type GmailListLabelsInputs = {
};

export type GmailListLabelsData = {
  LABELS: any;
  COUNT: any;
};

export type GmailListMessagesInputs = {
  maxResults: number;
  q: string;
};

export type GmailListMessagesData = {
  MESSAGES: any;
  NEXT_PAGE_TOKEN: any;
};

export type GmailSendEmailInputs = {
  raw: string;
};

export type GmailSendEmailData = {
  MESSAGE_ID: any;
  THREAD_ID: any;
};
