// This file is auto-generated by scripts/generate-warp-types.js

export type WhatsAppPairPersonalInputs = {
};

export type WhatsAppUpdatePersonalCLIInputs = {
};

export type WhatsAppSendTextInputs = {
  phone: string;
  message: string;
};

export type WhatsAppSyncPersonalInputs = {
  webhookUrl: string;
  webhookSecret: string;
};
