// This file is auto-generated by scripts/generate-warp-types.js

export type SolanaAccountInfoInputs = {
  ADDRESS: string;
  COMMITMENT: string;
  ENCODING: string;
  METHOD: string;
  JSONRPC: string;
  REQUEST_ID: number;
};

export type SolanaAccountInfoData = {
  BALANCE_LAMPORTS: string;
  BALANCE_SOL: number;
  BALANCE_FORMATTED: string;
  OWNER: any;
  EXECUTABLE: boolean;
  RENT_EPOCH: any;
};

export type SolanaAccountNFTsInputs = {
  ADDRESS: string;
  COMMITMENT: string;
  PROGRAM_ID: string;
  ENCODING: string;
  METHOD: string;
  JSONRPC: string;
  REQUEST_ID: number;
};

export type SolanaAccountNFTsData = {
  TOKEN_ACCOUNTS: any;
  NFTS: any[];
  NFT_COUNT: number;
  NFTS_SUMMARY: any[];
};

export type SolanaAccountTokensInputs = {
  ADDRESS: string;
  COMMITMENT: string;
  PROGRAM_ID: string;
  ENCODING: string;
  METHOD: string;
  JSONRPC: string;
  REQUEST_ID: number;
};

export type SolanaAccountTokensData = {
  TOKEN_ACCOUNTS: any;
  TOKEN_COUNT: number;
  TOKENS_SUMMARY: any[];
};

export type SolanaAccountTransactionCountInputs = {
  ADDRESS: string;
  LIMIT: number;
  BEFORE: string;
  UNTIL: string;
  COMMITMENT: string;
  METHOD: string;
  JSONRPC: string;
  REQUEST_ID: number;
};

export type SolanaAccountTransactionCountData = {
  TRANSACTIONS: any;
  TRANSACTION_COUNT: number;
  COUNT_FORMATTED: string;
};

export type SolanaAccountTransactionsInputs = {
  ADDRESS: string;
  LIMIT: number;
  BEFORE: string;
  UNTIL: string;
  COMMITMENT: string;
  METHOD: string;
  JSONRPC: string;
  REQUEST_ID: number;
};

export type SolanaAccountTransactionsData = {
  TRANSACTIONS: any;
  TRANSACTION_COUNT: number;
  TRANSACTIONS_SUMMARY: any[];
};

export type SolanaBurnTokensInputs = {
  MINT_ADDRESS: string;
};

export type SolanaRevokeDelegateInputs = {
  MINT_ADDRESS: string;
};

export type SolanaTransferSPLTokenInputs = {
  TOKEN_MINT: string;
  RECEIVER_ADDRESS: string;
};
