// This file is auto-generated by scripts/generate-warp-types.js

export type SolanaAccountTransactionsInputs = {
  ADDRESS: string;
  LIMIT: number;
  BEFORE: string;
  UNTIL: string;
  COMMITMENT: string;
  METHOD: string;
  JSONRPC: string;
  REQUEST_ID: number;
};

export type SolanaAccountTransactionsData = {
  TRANSACTIONS: any;
  TRANSACTION_COUNT: number;
  TRANSACTIONS_SUMMARY: any[];
};
