// This file is auto-generated by scripts/generate-warp-types.js

export type CloudflareCreateDNSRecordInputs = {
  ZONE_ID: string;
  type: string;
  name: string;
  content: string;
  proxied: string;
  ttl: number;
};

export type CloudflareCreateDNSRecordData = {
  RECORD_ID: any;
  NAME: any;
  TYPE: any;
  CONTENT: any;
};

export type CloudflareDeleteDNSRecordInputs = {
  ZONE_ID: string;
  RECORD_ID: string;
};

export type CloudflareDeleteDNSRecordData = {
  DELETED_ID: any;
};

export type CloudflareKVReadInputs = {
  NAMESPACE_ID: string;
  KEY: string;
};

export type CloudflareKVReadData = {
  VALUE: any;
};

export type CloudflareKVWriteInputs = {
  NAMESPACE_ID: string;
  KEY: string;
  value: string;
};

export type CloudflareListDNSRecordsInputs = {
  ZONE_ID: string;
  type: string;
  name: string;
};

export type CloudflareListDNSRecordsData = {
  RECORDS: any;
  COUNT: any;
};

export type CloudflareListKVNamespacesInputs = {
};

export type CloudflareListKVNamespacesData = {
  NAMESPACES: any;
  COUNT: any;
};

export type CloudflareListWorkersInputs = {
};

export type CloudflareListWorkersData = {
  WORKERS: any;
  COUNT: any;
};

export type CloudflareListZonesInputs = {
  name: string;
  per_page: number;
};

export type CloudflareListZonesData = {
  ZONES: any;
  COUNT: any;
};

export type CloudflarePurgeCacheInputs = {
  ZONE_ID: string;
  purge_everything: string;
  files: string;
};

export type CloudflarePurgeCacheData = {
  ID: any;
};
