// This file is auto-generated by scripts/generate-warp-types.js

export type ResendSendEmailInputs = {
  from: string;
  to: string;
  subject: string;
  html: string;
  text: string;
  replyTo: string;
  cc: string;
  bcc: string;
};

export type ResendSendEmailData = {
  EMAIL_ID: any;
};
