// This file is auto-generated by scripts/generate-warp-types.js

export type JoAiChangelogEntryAddInputs = {
  type: string;
  title: string;
  version: string;
  description: string;
};

export type JoAiCreateAgentInputs = {
  name: string;
};

export type JoAiAgentNameUpdateInputs = {
  name: string;
};

export type JoAiAgentNameUpdateData = {
  AGENT_NAME: any;
};

export type JoAiPublishAgentInputs = {
};

export type JoAiSetBillingAddressInputs = {
  userId: string;
  firstName: string;
  lastName: string;
  country: string;
  vatId: string;
};

export type JoAiCreateBlueprintInputs = {
  name: string;
  description: string;
  agentId: string;
  config: string;
};

export type JoAiUpdateBlueprintInputs = {
  blueprintId: string;
  name: string;
  description: string;
  config: string;
};

export type JoAiBroadcastMessageInputs = {
  message: string;
  roomId: string;
};

export type JoAiUpdateCharacterInputs = {
  name: string;
  systemPrompt: string;
  bio: string;
};

export type JoAiListContactActivitiesInputs = {
  contactId: string;
};

export type JoAiDeleteContactActivityInputs = {
  contactId: string;
  activityId: string;
};

export type JoAiLogContactActivityInputs = {
  contactId: string;
  type: string;
  description: string;
};

export type JoAiCreateContactInputs = {
  name: string;
  email: string;
  phone: string;
  company: string;
  title: string;
  notes: string;
  tags: string;
};

export type JoAiDeleteContactInputs = {
  contactId: string;
};

export type JoAiSendContactMessageInputs = {
  integration: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type JoAiSendContactMessageData = {
  contactEmail: any;
  contactName: any;
};

export type JoAiUpdateContactInputs = {
  contactId: string;
  name: string;
  email: string;
  phone: string;
  company: string;
  title: string;
  tags: string;
};

export type JoAiCreateContractInputs = {
  name: string;
  description: string;
  type: string;
  chain: string;
};

export type JoAiDeleteContractInputs = {
  contractId: string;
};

export type JoAiDeployContractInputs = {
  contractId: string;
  version: string;
  network: string;
};

export type JoAiSetContractAddressInputs = {
  contractId: string;
  address: string;
  network: string;
};

export type JoAiUpdateContractInputs = {
  contractId: string;
  name: string;
  description: string;
};

export type JoAiUploadtoDeskInputs = {
  url: string;
  pin: string;
  room: string;
};

export type JoAiWeeklyDigestEmailInputs = {
  INTEREST: string;
  DIGESTS_JSON: string;
  name: string;
  subject: string;
  email_list_uuid: string;
  segment_uuid: string;
  template_uuid: string;
  fields: string;
};

export type JoAiWeeklyDigestEmailData = {
  CAMPAIGN_UUID: any;
  CAMPAIGN_NAME: any;
};

export type JoAiCreateDocumentInputs = {
  title: string;
  content: string;
};

export type JoAiCreateElementInputs = {
  name: string;
  type: string;
  content: string;
  prompt: string;
};

export type JoAiDeleteElementInputs = {
  agentId: string;
  elementId: string;
};

export type JoAiUpdateElementInputs = {
  agentId: string;
  elementId: string;
  name: string;
  type: string;
  content: string;
  prompt: string;
};

export type JoAiGenerateElementVariationInputs = {
  agentId: string;
  elementId: string;
  prompt: string;
};

export type JoAiCreateGoalInputs = {
  title: string;
  description: string;
  priority: string;
};

export type JoAiUpdateGoalInputs = {
  goalId: string;
  progress: number;
  status: string;
  notes: string;
};

export type JoAiRespondtoHookInputs = {
  requestId: string;
  decision: string;
};

export type JoAiIngestKnowledgeInputs = {
  content: string;
  sourceType: string;
  sourceProvider: string;
  sourceExternalId: string;
  title: string;
  primitives: string;
};

export type JoAiCreateActionItemInputs = {
  title: string;
  description: string;
  priority: string;
  dueDate: string;
};

export type JoAiDeleteItemInputs = {
  itemId: string;
};

export type JoAiUpdateItemInputs = {
  itemId: string;
  title: string;
  content: string;
  status: string;
};

export type JoAiBusinessIdentityVerificationInputs = {
  fullName: string;
  country: string;
  address: string;
  taxId: string;
  companyName: string;
};

export type JoAiIdentityVerificationInputs = {
  fullName: string;
  country: string;
  address: string;
  taxId: string;
  companyName: string;
};

export type JoAiDeleteMediaInputs = {
  agentId: string;
  mediaId: string;
};

export type JoAiUploadMediaInputs = {
  url: string;
  label: string;
  type: string;
};

export type JoAiStartMeetingInputs = {
};

export type JoAiCreateMemoryInputs = {
  content: string;
  category: string;
  tags: string;
  teamVisible: boolean;
};

export type JoAiUpdateMemoryInputs = {
  memoryId: string;
  content: string;
  category: string;
  tags: string;
};

export type JoAiSendGeneratedMessageInputs = {
  INSTRUCTION: string;
  DESTINATION: string;
};

export type JoAiSetNotificationPreferenceInputs = {
  app: string;
  channel: string;
  enabled: string;
  key: string;
  value: string;
  brand: string;
};

export type JoAiCreatePrivateAppInputs = {
  teamSlug: string;
  name: string;
  description: string;
};

export type JoAiCreatePrivateWarpInputs = {
  PAYLOAD: string;
};

export type JoAiUpdatePrivateWarpInputs = {
  identifier: string;
  PAYLOAD: string;
};

export type JoAiCreateProjectInputs = {
  name: string;
  description: string;
};

export type JoAiDeleteProjectInputs = {
  projectId: string;
};

export type JoAiCreateReminderInputs = {
  text: string;
  scheduledAt: string;
};

export type JoAiDeleteReminderInputs = {
  reminderId: string;
};

export type JoAiGetAgentSettingInputs = {
};

export type JoAiGetAgentSettingData = {
  VALUE: any;
};

export type JoAiSetAgentSettingInputs = {
  brand: string;
  key: string;
  value: string;
};

export type JoAiOpenIntegrationSettingsInputs = {
  integration: string;
};

export type JoAiOpenSettingsInputs = {
};

export type JoAiSetTeamSettingInputs = {
  brand: string;
  key: string;
  value: string;
};

export type JoAiProvisionSiteInputs = {
  brand: string;
  team: string;
  settings: string;
};

export type JoAiCreateSkillInputs = {
  name: string;
  description: string;
  content: string;
};

export type JoAiDeleteSkillInputs = {
  skillId: string;
};

export type JoAiUpdateSkillInputs = {
  skillId: string;
  name: string;
  description: string;
  content: string;
};

export type JoAiRecordStoreEntryInputs = {
  storeName: string;
  value: string;
  label: string;
};

export type JoAiCreateStoreInputs = {
  name: string;
  description: string;
  valueType: string;
  unit: string;
};

export type JoAiDeleteStoreInputs = {
  storeName: string;
};

export type JoAiListStoresInputs = {
};

export type JoAiQueryStoreDataInputs = {
  storeName: string;
  since: string;
  until: string;
  last: string;
};

export type JoAiOpenStudioInputs = {
};

export type JoAiStudioProduceInputs = {
  projectId: string;
};

export type JoAiStudioSendInputs = {
  message: string;
  projectId: string;
  outputType: string;
  sourceUrl: string;
};

export type JoAiDeleteScheduledTaskInputs = {
  taskId: string;
};

export type JoAiListScheduledTasksInputs = {
};

export type JoAiPauseorResumeScheduledTaskInputs = {
  taskId: string;
};

export type TeamNotifyMembersInputs = {
  TITLE: string;
  MESSAGE: string;
};

export type TeamNotifyMembersData = {
};

export type JoAiTrainfromURLInputs = {
  url: string;
  maxPages: string;
};

export type JoAiGenerateUpgradeLinkInputs = {
  teamSlug: string;
  plan: string;
};

export type JoAiGenerateUpgradeLinkData = {
  checkoutUrl: any;
};

export type JoAiCreateUserInputs = {
  email: string;
  verified: boolean;
};

export type JoAiCreateUserData = {
  userId: any;
};

export type JoAiUserNameUpdateInputs = {
  name: string;
};

export type JoAiUserNameUpdateData = {
  USER_NAME: any;
};

export type JoAiUserOnboardingInputs = {
  telegramUsername: string;
  biggestTimeWaster: string;
  primaryGoalAI: string;
  technicalComfortLevel: string;
  blockchainCryptoApps: string;
  aiToolsPaid: string;
};

export type JoAiUserOnboardingInputs = {
  userName: string;
  source: string;
  userMode: string;
};

export type JoAiListUserTeamsInputs = {
  userId: string;
};

export type JoAiListUserTeamsData = {
  teams: any;
};

export type JoAiCreateWalletInputs = {
  chain: string;
  next: string;
};
