// This file is auto-generated by scripts/generate-warp-types.js

export type JoAiChangelogEntryAddInputs = {
  type: string;
  title: string;
  version: string;
  description: string;
};

export type JoAiDeleteAddressInputs = {
  addressId: string;
};

export type JoAiListAddressesInputs = {
  type: string;
};

export type JoAiListAddressesData = {
  addresses: any;
};

export type JoAiStoreAddressInputs = {
  name: string;
  country: string;
  type: string;
  addressOne: string;
  city: string;
  zipCode: string;
  vatId: string;
  team: string;
};

export type JoAiStoreAddressData = {
  ADDRESS_ID: any;
  ADDRESS_NAME: any;
};

export type JoAiUpdateAddressInputs = {
  addressId: string;
  name: string;
  country: string;
  addressOne: string;
  city: string;
  zipCode: string;
  type: string;
};

export type JoAiCreateAgentInputs = {
  name: string;
};

export type JoAiAgentNameUpdateInputs = {
  name: string;
};

export type JoAiAgentNameUpdateData = {
  AGENT_NAME: any;
};

export type JoAiPublishAgentInputs = {
};

export type JoAiCreateAPITokenInputs = {
  name: string;
};

export type JoAiCreateAPITokenData = {
  TOKEN: any;
};

export type JoAiCreateBlueprintInputs = {
  name: string;
  description: string;
  agentId: string;
  config: string;
  team: string;
};

export type JoAiUpdateBlueprintInputs = {
  blueprintId: string;
  name: string;
  description: string;
  config: string;
  team: string;
};

export type JoAiBroadcastMessageInputs = {
  message: string;
  roomId: string;
};

export type JoAiCreateCampaignInputs = {
  name: string;
  channel: string;
  subject: string;
  content: string;
  tags: string;
  contactIds: string;
  segmentId: string;
  team: string;
};

export type JoAiCreateCampaignData = {
  CAMPAIGN_ID: any;
  CAMPAIGN_NAME: any;
  CAMPAIGN_TOTAL: any;
};

export type JoAiDeleteCampaignInputs = {
  campaign_id: string;
  team: string;
};

export type JoAiSendCampaigntoContactInputs = {
  campaign_id: string;
  email: string;
  name: string;
  delay: string;
  team: string;
};

export type JoAiSendCampaignInputs = {
  campaign_id: string;
  team: string;
};

export type JoAiSendCampaignData = {
  CAMPAIGN_ID: any;
  CAMPAIGN_NAME: any;
  CAMPAIGN_STATUS: any;
};

export type JoAiUpdateCharacterInputs = {
  name: string;
  systemPrompt: string;
  bio: string;
};

export type JoAiCheckoutFulfillmentLocationsInputs = {
  team: string;
};

export type JoAiCheckoutFulfillmentLocationsData = {
  LOCATIONS: any;
};

export type JoAiPlaceCheckoutOrderInputs = {
  items: string;
  fulfillmentMethod: string;
  guest: string;
  billingAddress: string;
  shippingAddress: string;
  idempotencyKey: string;
  notes: string;
  sendConfirmation: boolean;
  team: string;
};

export type JoAiPlaceCheckoutOrderData = {
  ORDER_ID: any;
  ORDER_STATUS: any;
  PAYMENT_URL: any;
  ORDER_ACCESS_TOKEN: any;
};

export type JoAiCheckoutShippingRatesInputs = {
  items: string;
  'address.country': string;
  'address.zipCode': string;
  team: string;
};

export type JoAiCheckoutShippingRatesData = {
  SHIPPING_RATES: any;
};

export type JoAiCheckoutSnapshotInputs = {
  items: string;
  fulfillmentMethod: string;
  billingAddressId: string;
  shippingAddressId: string;
  shippingRateId: string;
  fulfillmentLocationId: string;
  team: string;
};

export type JoAiCheckoutSnapshotData = {
  SNAPSHOT_ID: any;
  SNAPSHOT_TOTALS: any;
  SNAPSHOT_ACCESS_TOKEN: any;
};

export type JoAiDeleteContactActivityInputs = {
  contactId: string;
  activityId: string;
  team: string;
};

export type JoAiLogContactActivityInputs = {
  contactId: string;
  type: string;
  description: string;
  meta: string;
  team: string;
};

export type JoAiCreateContactInputs = {
  name: string;
  email: string;
  phone: string;
  company: string;
  title: string;
  notes: string;
  tags: string;
  website: string;
  birthday: string;
  socials: string;
  team: string;
};

export type JoAiDeleteContactInputs = {
  contactId: string;
  team: string;
};

export type JoAiFindorCreateContactInputs = {
  name: string;
  email: string;
  phone: string;
  company: string;
  tags: string;
  team: string;
};

export type JoAiFindorCreateContactData = {
  contactId: any;
};

export type JoAiDraftContactMessageInputs = {
  contactId: string;
  reason: string;
  context: string;
  team: string;
};

export type JoAiDraftContactMessageData = {
  DRAFT: any;
};

export type JoAiSendContactMessageInputs = {
  team: string;
  integration: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type JoAiSendContactMessageData = {
  contactEmail: any;
  contactName: any;
};

export type JoAiSetContactPropertyInputs = {
  contactId: string;
  key: string;
  value: string;
  team: string;
};

export type JoAiUpdateContactInputs = {
  contactId: string;
  name: string;
  email: string;
  phone: string;
  company: string;
  title: string;
  notes: string;
  website: string;
  birthday: string;
  socials: string;
  tags: string;
  tagsAppend: string;
  nextFollowUpAt: string;
  followUpNote: string;
  team: string;
};

export type JoAiCreateContractInputs = {
  name: string;
  description: string;
  type: string;
  chain: string;
  team: string;
};

export type JoAiDeleteContractInputs = {
  contractId: string;
  team: string;
};

export type JoAiDeployContractInputs = {
  contractId: string;
  version: string;
  network: string;
  team: string;
};

export type JoAiSetContractAddressInputs = {
  contractId: string;
  address: string;
  network: string;
  team: string;
};

export type JoAiUpdateContractInputs = {
  contractId: string;
  name: string;
  description: string;
  team: string;
};

export type JoAiCreateCouponInputs = {
  code: string;
  percent: string;
  amount: string;
  condition: string;
  usesLeft: string;
  expiresAt: string;
  team: string;
};

export type JoAiCreateCouponData = {
  COUPON_ID: any;
  COUPON_CODE: any;
};

export type JoAiDeleteCouponInputs = {
  coupon_id: string;
  team: string;
};

export type JoAiUpdateCouponInputs = {
  coupon_id: string;
  code: string;
  percent: string;
  amount: string;
  condition: string;
  usesLeft: string;
  expiresAt: string;
  team: string;
};

export type JoAiUpdateCouponData = {
  COUPON_ID: any;
  COUPON_CODE: any;
};

export type JoAiUploadtoDeskInputs = {
  url: string;
  pin: boolean;
  room: string;
};

export type JoAiWeeklyDigestEmailInputs = {
  INTEREST: string;
  DIGESTS_JSON: string;
  name: string;
  subject: string;
  email_list_uuid: string;
  segment_uuid: string;
  template_uuid: string;
  fields: string;
};

export type JoAiWeeklyDigestEmailData = {
  CAMPAIGN_UUID: any;
  CAMPAIGN_NAME: any;
};

export type JoAiCreateDocumentInputs = {
  title: string;
  content: string;
  type: string;
  slug: string;
  app: string;
  channel: string;
  step: string;
  delay_days: string;
  locale: string;
  variables: string;
};

export type JoAiDeleteDocumentInputs = {
  documentId: string;
};

export type JoAiUpdateDocumentInputs = {
  documentId: string;
  title: string;
  content: string;
  slug: string;
  app: string;
  channel: string;
  step: string;
  delay_days: string;
  variables: string;
};

export type JoAiCreateElementInputs = {
  name: string;
  type: string;
  content: string;
  prompt: string;
};

export type JoAiDeleteElementInputs = {
  elementId: string;
};

export type JoAiUpdateElementInputs = {
  elementId: string;
  name: string;
  type: string;
  content: string;
  prompt: string;
};

export type JoAiDeleteElementVariationInputs = {
  elementId: string;
  variationId: string;
};

export type JoAiGenerateElementVariationInputs = {
  elementId: string;
  prompt: string;
};

export type JoAiUpdateElementVariationInputs = {
  elementId: string;
  variationId: string;
  label: string;
  aspectRatio: string;
};

export type JoAiCreateFulfillmentInputs = {
  orderId: string;
  items: string;
  carrierCode: string;
  trackingNumber: string;
  trackingUrl: string;
  team: string;
};

export type JoAiCreateFulfillmentData = {
  FULFILLMENT_ID: any;
  FULFILLMENT_STATUS: any;
};

export type JoAiListFulfillmentsInputs = {
  orderId: string;
  team: string;
};

export type JoAiCreateFulfillmentLocationInputs = {
  name: string;
  addressId: string;
  instructions: string;
  active: string;
  team: string;
};

export type JoAiCreateFulfillmentLocationData = {
  LOCATION_ID: any;
  LOCATION_NAME: any;
};

export type JoAiDeleteFulfillmentLocationInputs = {
  locationId: string;
  team: string;
};

export type JoAiListFulfillmentLocationsInputs = {
  team: string;
};

export type JoAiUpdateFulfillmentLocationInputs = {
  locationId: string;
  name: string;
  addressId: string;
  instructions: string;
  active: string;
  team: string;
};

export type JoAiUpdateFulfillmentLocationData = {
  LOCATION_ID: any;
  LOCATION_NAME: any;
};

export type JoAiUpdateFulfillmentInputs = {
  orderId: string;
  fulfillmentId: string;
  status: string;
  team: string;
};

export type JoAiUpdateFulfillmentData = {
  FULFILLMENT_ID: any;
  FULFILLMENT_STATUS: any;
};

export type JoAiCreateGoalInputs = {
  title: string;
  description: string;
  priority: string;
};

export type JoAiUpdateGoalInputs = {
  goalId: string;
  progress: number;
  status: string;
  notes: string;
};

export type JoAiCreateHookInputs = {
  source: string;
  warpIdentifier: string;
  event: string;
  tag: string;
  name: string;
  url: string;
};

export type JoAiDeleteHookInputs = {
  hookId: string;
};

export type JoAiRespondtoHookInputs = {
  requestId: string;
  decision: string;
};

export type JoAiToggleHookInputs = {
  hookId: string;
};

export type JoAiIngestKnowledgeInputs = {
  content: string;
  sourceType: string;
  sourceProvider: string;
  sourceExternalId: string;
  title: string;
  primitives: string;
};

export type JoAiCreateActionItemInputs = {
  title: string;
  description: string;
  priority: string;
  dueDate: string;
  tags: string;
  goalId: string;
  status: string;
  contactIds: string;
  meta: string;
};

export type JoAiDeleteItemInputs = {
  itemId: string;
};

export type JoAiUpdateItemInputs = {
  itemId: string;
  title: string;
  content: string;
  status: string;
};

export type JoAiRecordKVEntryInputs = {
  field: string;
  value: string;
  label: string;
};

export type JoAiCreateKVInputs = {
  name: string;
  description: string;
  valueType: string;
  unit: string;
};

export type JoAiDeleteKVInputs = {
  field: string;
};

export type JoAiGetKVValueInputs = {
  field: string;
};

export type JoAiListKVInputs = {
};

export type JoAiQueryKVDataInputs = {
  field: string;
  since: string;
  until: string;
  last: string;
  cursor: string;
};

export type JoAiSetKVFieldInputs = {
  field: string;
  value: string;
  label: string;
};

export type JoAiToggleKVFieldInputs = {
  field: string;
};

export type JoAiBusinessIdentityVerificationInputs = {
  fullName: string;
  country: string;
  address: string;
  taxId: string;
  companyName: string;
};

export type JoAiIdentityVerificationInputs = {
  fullName: string;
  country: string;
  address: string;
  taxId: string;
  companyName: string;
};

export type JoAiCreateLinkInputs = {
  title: string;
  url: string;
  team: string;
};

export type JoAiCreateLinkData = {
  SHORT_URL: any;
  SLUG: any;
};

export type JoAiListLinksInputs = {
  team: string;
};

export type JoAiEnrollinLoyaltyProgramInputs = {
  contactId: string;
  team: string;
};

export type JoAiEnrollinLoyaltyProgramData = {
  contactId: any;
  points: any;
};

export type JoAiLoyaltySignupEmailInputs = {
  name: string;
  email: string;
  team: string;
};

export type JoAiLoyaltySignupEmailData = {
  contactId: any;
  passUrl: any;
};

export type JoAiLoyaltySignupWhatsAppInputs = {
  name: string;
  phone: string;
  team: string;
};

export type JoAiLoyaltySignupWhatsAppData = {
  contactId: any;
  passUrl: any;
};

export type JoAiDeleteMediaInputs = {
  mediaId: string;
  team: string;
};

export type JoAiStartMeetingInputs = {
};

export type JoAiCreateMemoryInputs = {
  content: string;
  category: string;
  tags: string;
  teamVisible: boolean;
  confidence: number;
  stateful: boolean;
  importance: number;
  entities: string;
  sentiment: number;
  temporal: string;
};

export type JoAiUpdateMemoryInputs = {
  memoryId: string;
  content: string;
  category: string;
  tags: string;
  stateful: boolean;
  importance: number;
  entities: string;
  sentiment: number;
  temporal: string;
  tier: string;
};

export type JoAiSendGeneratedMessageInputs = {
  INSTRUCTION: string;
  DESTINATION: string;
};

export type JoAiSendGeneratedMessageData = {
  MESSAGE: any;
};

export type JoAiSendMessageInputs = {
  message: string;
  destination: string;
};

export type JoAiSetNotificationPreferenceInputs = {
  app: string;
  channel: string;
  enabled: string;
  key: string;
  value: string;
  brand: string;
};

export type JoAiCreateOrderInputs = {
  contactName: string;
  billItem: string;
  type: string;
  notes: string;
  priceMode: string;
  contactId: string;
  serviceIds: string;
  team: string;
};

export type JoAiCreateOrderData = {
  id: any;
  total: any;
  totalDisplay: number;
  invoiceUrl: any;
  paymentUrl: any;
  status: any;
};

export type JoAiDeleteOrderInputs = {
  order_id: string;
  team: string;
};

export type JoAiGetOrderInputs = {
  orderId: string;
  orderAccessToken: string;
  team: string;
};

export type JoAiGetOrderData = {
  ORDER_ID: any;
  ORDER_STATUS: any;
  ORDER_TOTAL: any;
  PAYMENT_URL: any;
};

export type JoAiPayOrderInputs = {
  orderId: string;
  orderAccessToken: string;
  team: string;
};

export type JoAiPayOrderData = {
  PAYMENT_URL: any;
};

export type JoAiCreatePortalSessionInputs = {
  redirect: string;
};

export type JoAiCreatePortalSessionData = {
  portalUrl: any;
};

export type JoAiCreatePrivateAppInputs = {
  name: string;
  description: string;
  public: boolean;
  team: string;
};

export type JoAiCreatePrivateWarpInputs = {
  brand: string;
  definition: string;
  public: boolean;
  form: boolean;
  store: boolean;
  extras: string;
  team: string;
};

export type JoAiDeletePrivateWarpInputs = {
  identifier: string;
};

export type JoAiUpdatePrivateWarpInputs = {
  identifier: string;
  PAYLOAD: string;
  team: string;
};

export type JoAiCreateProductInputs = {
  name: string;
  price: number;
  unit: string;
  tags: string;
  description: string;
  public: string;
  team: string;
};

export type JoAiCreateProductData = {
  id: any;
  name: any;
};

export type JoAiDeleteProductInputs = {
  product_id: string;
  team: string;
};

export type JoAiUpdateProductInputs = {
  product_id: string;
  name: string;
  unit: string;
  tags: string;
  description: string;
  active: string;
  virtual: string;
  public: string;
  media: string;
  team: string;
};

export type JoAiUpdateProductData = {
  PRODUCT_ID: any;
  PRODUCT_NAME: any;
};

export type JoAiCreateProductVariationInputs = {
  productId: string;
  name: string;
  sku: string;
  price: number;
  type: string;
  meta: string;
  team: string;
};

export type JoAiUpdateProductVariationInputs = {
  variationId: string;
  price: number;
  name: string;
  active: string;
  team: string;
};

export type JoAiCreateProjectInputs = {
  name: string;
  brief: string;
};

export type JoAiDeleteProjectInputs = {
  projectId: string;
};

export type JoAiCreateReminderInputs = {
  text: string;
  scheduledAt: string;
};

export type JoAiDeleteReminderInputs = {
  reminderId: string;
};

export type JoAiCreateReturnInputs = {
  orderId: string;
  orderAccessToken: string;
  reason: string;
  items: string;
  fulfillmentId: string;
  team: string;
};

export type JoAiCreateReturnData = {
  RETURN_ID: any;
  RETURN_STATUS: any;
};

export type JoAiListReturnsInputs = {
  orderId: string;
  orderAccessToken: string;
  team: string;
};

export type JoAiUpdateReturnInputs = {
  returnId: string;
  status: string;
  merchantNote: string;
  refundAmount: string;
  team: string;
};

export type JoAiUpdateReturnData = {
  RETURN_ID: any;
  RETURN_STATUS: any;
};

export type JoAiCreateSegmentInputs = {
  name: string;
  conditions: string;
  team: string;
};

export type JoAiCreateSegmentData = {
  SEGMENT_ID: any;
  SEGMENT_NAME: any;
  SEGMENT_COUNT: number;
};

export type JoAiDeleteSegmentInputs = {
  segment_id: string;
  team: string;
};

export type JoAiCreateServiceInputs = {
  name: string;
  price: number;
  pricingModel: string;
  durationMinutes: string;
  description: string;
  tags: string;
  digital: string;
  public: string;
  team: string;
};

export type JoAiCreateServiceData = {
  id: any;
  name: any;
  price: any;
  priceDisplay: number;
};

export type JoAiDeleteServiceInputs = {
  service_id: string;
  team: string;
};

export type JoAiUpdateServiceInputs = {
  service_id: string;
  name: string;
  price: string;
  durationMinutes: string;
  tags: string;
  description: string;
  active: string;
  digital: string;
  public: string;
  team: string;
};

export type JoAiUpdateServiceData = {
  SERVICE_ID: any;
  SERVICE_NAME: any;
};

export type JoAiGetAgentSettingInputs = {
};

export type JoAiGetAgentSettingData = {
  VALUE: any;
};

export type JoAiSetAgentSettingInputs = {
  brand: string;
  key: string;
  value: string;
};

export type JoAiOpenIntegrationSettingsInputs = {
  integration: string;
};

export type JoAiOpenSettingsInputs = {
};

export type JoAiSetTeamSettingInputs = {
  brand: string;
  key: string;
  value: string;
  team: string;
};

export type JoAiCreateShippingRateInputs = {
  zoneId: string;
  name: string;
  price: string;
  freeShippingThreshold: string;
  minOrderValue: string;
  maxOrderValue: string;
  minWeight: string;
  maxWeight: string;
  estimatedMinDays: string;
  estimatedMaxDays: string;
  active: string;
  team: string;
};

export type JoAiCreateShippingRateData = {
  RATE_ID: any;
  RATE_NAME: any;
};

export type JoAiDeleteShippingRateInputs = {
  zoneId: string;
  rateId: string;
  team: string;
};

export type JoAiUpdateShippingRateInputs = {
  zoneId: string;
  rateId: string;
  name: string;
  price: string;
  freeShippingThreshold: string;
  minOrderValue: string;
  maxOrderValue: string;
  minWeight: string;
  maxWeight: string;
  estimatedMinDays: string;
  estimatedMaxDays: string;
  active: string;
  team: string;
};

export type JoAiUpdateShippingRateData = {
  RATE_ID: any;
  RATE_NAME: any;
};

export type JoAiCreateShippingZoneInputs = {
  name: string;
  countries: string;
  postalCodeRules: string;
  active: string;
  team: string;
};

export type JoAiCreateShippingZoneData = {
  ZONE_ID: any;
  ZONE_NAME: any;
};

export type JoAiDeleteShippingZoneInputs = {
  zoneId: string;
  team: string;
};

export type JoAiListShippingZonesInputs = {
  team: string;
};

export type JoAiUpdateShippingZoneInputs = {
  zoneId: string;
  name: string;
  countries: string;
  postalCodeRules: string;
  active: string;
  team: string;
};

export type JoAiUpdateShippingZoneData = {
  ZONE_ID: any;
  ZONE_NAME: any;
};

export type JoAiProvisionSiteInputs = {
  brand: string;
  team: string;
  settings: string;
  next: string;
};

export type JoAiProvisionSiteData = {
  SITE_URL: any;
};

export type JoAiCreateSkillInputs = {
  name: string;
  description: string;
  content: string;
  team: string;
};

export type JoAiDeleteSkillInputs = {
  skillId: string;
  team: string;
};

export type JoAiUpdateSkillInputs = {
  skillId: string;
  name: string;
  description: string;
  content: string;
  team: string;
};

export type JoAiStudioExportInputs = {
  projectId: string;
};

export type JoAiOpenStudioInputs = {
};

export type JoAiStudioProduceInputs = {
  projectId: string;
};

export type JoAiStudioSendInputs = {
  message: string;
  projectId: string;
  outputType: string;
  sourceUrl: string;
  references: string;
};

export type JoAiCancelSubscriptionInputs = {
  subscriptionId: string;
  team: string;
};

export type JoAiUpdateSubscriptionDeliveryInputs = {
  subscriptionId: string;
  fulfillmentMethod: string;
  shippingAddressId: string;
  shippingRateId: string;
  fulfillmentLocationId: string;
  team: string;
};

export type JoAiListSubscriptionsInputs = {
  team: string;
};

export type JoAiPauseSubscriptionDeliveryInputs = {
  subscriptionId: string;
  team: string;
};

export type JoAiResumeSubscriptionDeliveryInputs = {
  subscriptionId: string;
  team: string;
};

export type JoAiResumeSubscriptionInputs = {
  subscriptionId: string;
  team: string;
};

export type JoAiShowSubscriptionInputs = {
  subscriptionId: string;
  team: string;
};

export type JoAiSkipSubscriptionDeliveryInputs = {
  subscriptionId: string;
  team: string;
};

export type JoAiCreateScheduledTaskInputs = {
  warp: string;
  cronExpression: string;
  inputs: string;
  maxRuns: number;
  startsAt: string;
  endsAt: string;
  agent: string;
};

export type JoAiDeleteScheduledTaskInputs = {
  taskId: string;
};

export type JoAiPauseorResumeScheduledTaskInputs = {
  taskId: string;
};

export type JoAiCreateTeamInputs = {
  name: string;
  public: string;
  locale: string;
  tags: string;
  category: string;
  tagline: string;
  description: string;
  website: string;
  phone: string;
  email: string;
  address: string;
  location: string;
  settings: string;
};

export type JoAiCreateTeamData = {
  TEAM_ID: any;
  TEAM_NAME: any;
  TEAM_SLUG: any;
};

export type TeamNotifyMembersInputs = {
  TITLE: string;
  MESSAGE: string;
};

export type TeamNotifyMembersData = {
};

export type JoAiSetTeamMetaInputs = {
  slug: string;
  key: string;
  value: string;
};

export type JoAiUpdateTeamPlaceInputs = {
  slug: string;
  sourceId: string;
};

export type JoAiUpdateTeamInputs = {
  slug: string;
  name: string;
  public: string;
  tags: string;
  category: string;
  tagline: string;
  description: string;
  website: string;
  phone: string;
  email: string;
  address: string;
  location: string;
  logoMediaId: string;
  coverMediaId: string;
};

export type JoAiUpdateTeamData = {
  TEAM_ID: any;
  TEAM_NAME: any;
  TEAM_SLUG: any;
};

export type JoAiTrainfromURLInputs = {
  url: string;
  maxPages: string;
};

export type JoAiCreateUpdateInputs = {
  title: string;
  type: string;
  body: string;
  startsAt: string;
  endsAt: string;
  status: string;
  linkUrl: string;
  team: string;
};

export type JoAiCreateUpdateData = {
  UPDATE_ID: any;
  UPDATE_TITLE: any;
};

export type JoAiDeleteUpdateInputs = {
  updateId: string;
  team: string;
};

export type JoAiUpdateUpdateInputs = {
  updateId: string;
  title: string;
  type: string;
  body: string;
  startsAt: string;
  endsAt: string;
  status: string;
  linkUrl: string;
  team: string;
};

export type JoAiUpdateUpdateData = {
  UPDATE_ID: any;
  UPDATE_TITLE: any;
};

export type JoAiGenerateUpgradeLinkInputs = {
  teamSlug: string;
  plan: string;
};

export type JoAiGenerateUpgradeLinkData = {
  checkoutUrl: any;
};

export type JoAiCreateUserInputs = {
  email: string;
  verified: boolean;
};

export type JoAiCreateUserData = {
  userId: any;
  personalTeamSlug: any;
};

export type JoAiUserNameUpdateInputs = {
  name: string;
};

export type JoAiUserNameUpdateData = {
  USER_NAME: any;
};

export type JoAiUserOnboardingInputs = {
  userName: string;
  source: string;
  userMode: string;
};

export type JoAiListUserTeamsInputs = {
  userId: string;
};

export type JoAiListUserTeamsData = {
  teams: any;
};

export type JoAiCreateWalletInputs = {
  chain: string;
  next: string;
};
