// This file is auto-generated by scripts/generate-warp-types.js

export type FigmaGetFileInputs = {
  FILE_KEY: string;
};

export type FigmaGetFileData = {
  NAME: any;
  LAST_MODIFIED: any;
  THUMBNAIL: any;
};
