// This file is auto-generated by scripts/generate-warp-types.js

export type AllowanceFundAgentInputs = {
  chain: string;
  agent: string;
  per_tx_limit: string;
  period_limit: string;
  period_type: string;
  expires_at: string;
  payment: string;
};

export type AllowancePauseInputs = {
  chain: string;
  allowance_id: string;
};

export type AllowanceRevokeInputs = {
  chain: string;
  allowance_id: string;
};

export type AllowanceSpendCallInputs = {
  chain: string;
  allowance_id: string;
  amount: string;
  destination: string;
  endpoint_name: string;
  gas_limit: string;
};

export type AllowanceSpendInputs = {
  chain: string;
  allowance_id: string;
  amount: string;
  destination: string;
};

export type AllowanceViewAgentIDsInputs = {
  chain: string;
  agent: string;
};

export type AllowanceViewAgentIDsData = {
  IDS: any;
  COUNT: number;
};

export type AllowanceViewOwnerIDsInputs = {
  chain: string;
  owner: string;
};

export type AllowanceViewOwnerIDsData = {
  IDS: any;
  COUNT: number;
};

export type AllowanceViewInputs = {
  chain: string;
  allowance_id: string;
};

export type AllowanceViewData = {
  ALLOWANCE: any;
  TOKEN: string;
  BALANCE_RAW: string;
  BALANCE: number;
  BALANCE_FORMATTED: string;
  STATUS: string;
};

export type AllowanceManageWhitelistInputs = {
  chain: string;
  allowance_id: string;
  destination: string;
};
