// This file is auto-generated by scripts/generate-warp-types.js

export type EmailSendInputs = {
  integration: string;
  recipientId: string;
  recipientName: string;
  subject: string;
  message: string;
};

export type EmailSendData = {
  EMAIL_ROOM_ID: any;
  EMAIL_MESSAGE_ID: any;
  EMAIL_MAILTO_URL: string;
};
