// This file is auto-generated by scripts/generate-warp-types.js

export type JoAiListCampaignsInputs = {
  team: string;
  page: string;
};

export type JoAiListCampaignsData = {
  campaigns: any;
  campaignsList: any;
  campaignsCount: any;
};
