// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleFormsListResponsesInputs = {
  FORM_ID: string;
  pageSize: number;
};

export type GoogleFormsListResponsesData = {
  RESPONSES: any;
  COUNT: any;
};
