// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleFormsGetFormInputs = {
  FORM_ID: string;
};

export type GoogleFormsGetFormData = {
  FORM_ID: any;
  TITLE: any;
  DOCUMENT_TITLE: any;
};

export type GoogleFormsListResponsesInputs = {
  FORM_ID: string;
  pageSize: number;
};

export type GoogleFormsListResponsesData = {
  RESPONSES: any;
  COUNT: any;
};
