// This file is auto-generated by scripts/generate-warp-types.js

export type JiraCreateIssueInputs = {
  projectKey: string;
  summary: string;
  issuetype: string;
  description: string;
};

export type JiraCreateIssueData = {
  ISSUE_ID: any;
  ISSUE_KEY: any;
  ISSUE_URL: any;
};

export type JiraGetIssueInputs = {
  ISSUE_KEY: string;
};

export type JiraGetIssueData = {
  KEY: any;
  SUMMARY: any;
  STATUS: string;
  ASSIGNEE: any;
};
