// This file is auto-generated by scripts/generate-warp-types.js

export type JiraGetIssueInputs = {
  AUTH_HEADER: string;
  ISSUE_KEY: string;
};

export type JiraGetIssueData = {
  KEY: any;
  SUMMARY: any;
  STATUS: string;
  ASSIGNEE: any;
};
