// This file is auto-generated by scripts/generate-warp-types.js

export type LoyaltyConfigureInputs = {
  stampsForReward: string;
  rewardLabel: string;
  reviewUrl: string;
  reviewDiscount: string;
  reminderDays: string;
};

export type LoyaltyCreateInputs = {
};

export type LoyaltyRedeemRewardInputs = {
};

export type LoyaltyRedeemRewardData = {
  NAME: any;
};

export type LoyaltyRegisterInputs = {
  name: string;
  email: string;
  phone: string;
  card: string;
};

export type LoyaltyRegisterData = {
  IS_REGISTERED: boolean;
};

export type LoyaltyReminderInputs = {
};

export type LoyaltyReminderData = {
  REMINDER_DAYS: any;
  STALE_CUSTOMERS: any;
};

export type LoyaltyReviewPromptInputs = {
};

export type LoyaltyReviewPromptData = {
  REVIEW_URL: any;
  REVIEW_DISCOUNT: any;
};

export type LoyaltyNFCSetupInputs = {
};

export type LoyaltyNFCSetupData = {
  nfc: any;
};

export type LoyaltyStampInputs = {
};

export type LoyaltyStampData = {
  NAME: any;
  STAMPS: any;
  NEEDED: any;
  DISCOUNT: any;
  REWARD_READY: any;
};

export type LoyaltyStatusInputs = {
};

export type LoyaltyStatusData = {
  NAME: any;
  STAMPS: any;
  NEEDED: any;
  DISCOUNT: any;
  REWARD_READY: any;
  LAST_VISIT: any;
};
