// This file is auto-generated by scripts/generate-warp-types.js

export type ContentCreatePostInputs = {
  message: string;
  outputFormats: string;
};

export type ContentCreatePromotionInputs = {
  message: string;
  outputFormats: string;
};

export type ContentCreateStoryInputs = {
  message: string;
  outputFormats: string;
};

export type ContentMonthlyReportInputs = {
};

export type ContentSuggestIdeasInputs = {
  niche: string;
  timeframe: string;
};

export type ContentWeeklySuggestionsInputs = {
};
