// This file is auto-generated by scripts/generate-warp-types.js

export type MailcoachAddSubscriberTagsInputs = {
  SUBSCRIBER_UUID: string;
  tags: string;
};

export type MailcoachAddSubscriberTagsData = {
};

export type MailcoachAddSuppressionInputs = {
  email: string;
  reason: string;
};

export type MailcoachAddSuppressionData = {
  SUPPRESSION_UUID: any;
};

export type MailcoachAppendSubscriberImportInputs = {
  IMPORT_UUID: string;
  subscribers_csv: string;
};

export type MailcoachAppendSubscriberImportData = {
  IMPORT_UUID: any;
  STATUS: string;
};

export type MailcoachConfirmSubscriberInputs = {
  SUBSCRIBER_UUID: string;
};

export type MailcoachConfirmSubscriberData = {
};

export type MailcoachCreateCampaignInputs = {
  name: string;
  email_list_uuid: string;
  subject: string;
  from_email: string;
  html: string;
  template_uuid: string;
  fields: string;
  schedule_at: string;
};

export type MailcoachCreateCampaignData = {
  CAMPAIGN_UUID: any;
  CAMPAIGN_NAME: any;
  STATUS: string;
};

export type MailcoachCreateEmailListInputs = {
  name: string;
  default_from_email: string;
  default_from_name: string;
  default_reply_to_email: string;
  requires_confirmation: boolean;
};

export type MailcoachCreateEmailListData = {
  LIST_UUID: any;
  LIST_NAME: any;
};

export type MailcoachCreateSegmentInputs = {
  LIST_UUID: string;
  name: string;
  positive_tags: string;
  negative_tags: string;
  all_positive_tags_required: boolean;
};

export type MailcoachCreateSegmentData = {
  SEGMENT_UUID: any;
  SEGMENT_NAME: any;
};

export type MailcoachCreateSubscriberImportInputs = {
  email_list_uuid: string;
  subscribers_csv: string;
  subscribe_unsubscribed: boolean;
  unsubscribe_others: boolean;
  replace_tags: boolean;
};

export type MailcoachCreateSubscriberImportData = {
  IMPORT_UUID: any;
  STATUS: string;
};

export type MailcoachCreateTagInputs = {
  LIST_UUID: string;
  name: string;
  visible_in_preferences: boolean;
};

export type MailcoachCreateTagData = {
  TAG_UUID: any;
  TAG_NAME: any;
};

export type MailcoachCreateTemplateInputs = {
  name: string;
  html: string;
};

export type MailcoachCreateTemplateData = {
  TEMPLATE_UUID: any;
  TEMPLATE_NAME: any;
};

export type MailcoachDeleteCampaignInputs = {
  CAMPAIGN_UUID: string;
};

export type MailcoachDeleteCampaignData = {
};

export type MailcoachDeleteEmailListInputs = {
  LIST_UUID: string;
};

export type MailcoachDeleteEmailListData = {
};

export type MailcoachDeleteSegmentInputs = {
  LIST_UUID: string;
  SEGMENT_UUID: string;
};

export type MailcoachDeleteSegmentData = {
};

export type MailcoachDeleteSendInputs = {
  SEND_UUID: string;
};

export type MailcoachDeleteSendData = {
};

export type MailcoachDeleteSubscriberImportInputs = {
  IMPORT_UUID: string;
};

export type MailcoachDeleteSubscriberImportData = {
};

export type MailcoachDeleteSubscriberInputs = {
  SUBSCRIBER_UUID: string;
};

export type MailcoachDeleteSubscriberData = {
};

export type MailcoachDeleteTagInputs = {
  LIST_UUID: string;
  TAG_UUID: string;
};

export type MailcoachDeleteTagData = {
};

export type MailcoachDeleteTemplateInputs = {
  TEMPLATE_UUID: string;
};

export type MailcoachDeleteTemplateData = {
};

export type MailcoachGetCampaignBouncesInputs = {
  CAMPAIGN_UUID: string;
  'filter[type]': string;
  per_page: number;
};

export type MailcoachGetCampaignBouncesData = {
  BOUNCES: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachGetCampaignClicksInputs = {
  CAMPAIGN_UUID: string;
  sort: string;
  per_page: number;
};

export type MailcoachGetCampaignClicksData = {
  CLICKS: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachGetCampaignOpensInputs = {
  CAMPAIGN_UUID: string;
  'filter[search]': string;
  sort: string;
  per_page: number;
};

export type MailcoachGetCampaignOpensData = {
  OPENS: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachGetCampaignUnsubscribesInputs = {
  CAMPAIGN_UUID: string;
  per_page: number;
};

export type MailcoachGetCampaignUnsubscribesData = {
  UNSUBSCRIBES: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachGetCampaignInputs = {
  CAMPAIGN_UUID: string;
};

export type MailcoachGetCampaignData = {
  CAMPAIGN_DATA: any;
  CAMPAIGN_NAME: any;
  STATUS: string;
  OPEN_COUNT: number;
  CLICK_COUNT: number;
  SENT_COUNT: number;
};

export type MailcoachGetEmailListInputs = {
  LIST_UUID: string;
};

export type MailcoachGetEmailListData = {
  LIST_DATA: any;
  LIST_NAME: any;
  ACTIVE_SUBSCRIBERS: any;
};

export type MailcoachGetLinkInputs = {
  LINK_UUID: string;
};

export type MailcoachGetLinkData = {
  LINK_DATA: any;
  URL: any;
  UNIQUE_CLICK_COUNT: number;
  CLICK_COUNT: number;
};

export type MailcoachGetSegmentInputs = {
  LIST_UUID: string;
  SEGMENT_UUID: string;
};

export type MailcoachGetSegmentData = {
  SEGMENT_DATA: any;
  SEGMENT_NAME: any;
};

export type MailcoachGetSendInputs = {
  SEND_UUID: string;
};

export type MailcoachGetSendData = {
  SEND_DATA: any;
  OPEN_COUNT: number;
  CLICK_COUNT: number;
  FAILURE_REASON: any;
};

export type MailcoachGetSubscriberImportInputs = {
  IMPORT_UUID: string;
};

export type MailcoachGetSubscriberImportData = {
  IMPORT_DATA: any;
  STATUS: string;
  IMPORTED_SUBSCRIBERS_COUNT: number;
  ERROR_COUNT: number;
};

export type MailcoachGetSubscriberInputs = {
  SUBSCRIBER_UUID: string;
};

export type MailcoachGetSubscriberData = {
  SUBSCRIBER_DATA: any;
  EMAIL: any;
  STATUS: string;
  FIRST_NAME: any;
  LAST_NAME: any;
};

export type MailcoachGetSuppressionInputs = {
  EMAIL_OR_UUID: string;
};

export type MailcoachGetSuppressionData = {
  SUPPRESSION_DATA: any;
  EMAIL: any;
  REASON: any;
};

export type MailcoachGetTagInputs = {
  LIST_UUID: string;
  TAG_UUID: string;
};

export type MailcoachGetTagData = {
  TAG_DATA: any;
  TAG_NAME: any;
};

export type MailcoachGetTemplateInputs = {
  TEMPLATE_UUID: string;
};

export type MailcoachGetTemplateData = {
  TEMPLATE_DATA: any;
  TEMPLATE_NAME: any;
};

export type MailcoachGetTransactionalTemplateInputs = {
  TEMPLATE_UUID: string;
};

export type MailcoachGetTransactionalTemplateData = {
  TEMPLATE_DATA: any;
  TEMPLATE_NAME: any;
};

export type MailcoachListCampaignsInputs = {
  'filter[search]': string;
  'filter[status]': string;
  per_page: number;
};

export type MailcoachListCampaignsData = {
  CAMPAIGNS: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachListEmailListsInputs = {
  'filter[search]': string;
  sort: string;
  per_page: number;
};

export type MailcoachListEmailListsData = {
  LISTS: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachListSegmentsInputs = {
  LIST_UUID: string;
};

export type MailcoachListSegmentsData = {
  SEGMENTS: any;
  COUNT: number;
};

export type MailcoachListSendsInputs = {
  subscriber_uuid: string;
  campaign_uuid: string;
  per_page: number;
};

export type MailcoachListSendsData = {
  SENDS: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachListSubscriberImportsInputs = {
  per_page: number;
};

export type MailcoachListSubscriberImportsData = {
  IMPORTS: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachListSubscribersInputs = {
  LIST_UUID: string;
  'filter[search]': string;
  'filter[status]': string;
  per_page: number;
};

export type MailcoachListSubscribersData = {
  SUBSCRIBERS: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachListSuppressionsInputs = {
  'filter[search]': string;
  'filter[reason]': string;
  per_page: number;
};

export type MailcoachListSuppressionsData = {
  SUPPRESSIONS: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachListTagsInputs = {
  LIST_UUID: string;
};

export type MailcoachListTagsData = {
  TAGS: any;
  COUNT: number;
};

export type MailcoachListTemplatesInputs = {
  'filter[search]': string;
  sort: string;
};

export type MailcoachListTemplatesData = {
  TEMPLATES: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachListTransactionalTemplatesInputs = {
  'filter[name]': string;
  per_page: number;
};

export type MailcoachListTransactionalTemplatesData = {
  TEMPLATES: any;
  COUNT: number;
  TOTAL: any;
};

export type MailcoachRemoveSubscriberTagsInputs = {
  SUBSCRIBER_UUID: string;
  tags: string;
};

export type MailcoachRemoveSubscriberTagsData = {
};

export type MailcoachRemoveSuppressionInputs = {
  EMAIL_OR_UUID: string;
};

export type MailcoachRemoveSuppressionData = {
};

export type MailcoachResendConfirmationInputs = {
  SUBSCRIBER_UUID: string;
};

export type MailcoachResendConfirmationData = {
};

export type MailcoachSendCampaignInputs = {
  CAMPAIGN_UUID: string;
};

export type MailcoachSendCampaignData = {
};

export type MailcoachSendTestEmailInputs = {
  CAMPAIGN_UUID: string;
  email: string;
};

export type MailcoachSendTestEmailData = {
};

export type MailcoachSendTransactionalEmailInputs = {
  to: string;
  from: string;
  subject: string;
  mail_name: string;
  html: string;
  cc: string;
  bcc: string;
};

export type MailcoachSendTransactionalEmailData = {
  MAIL_UUID: any;
};

export type MailcoachStartSubscriberImportInputs = {
  IMPORT_UUID: string;
};

export type MailcoachStartSubscriberImportData = {
};

export type MailcoachSubscribeInputs = {
  LIST_UUID: string;
  email: string;
  first_name: string;
  last_name: string;
  tags: string;
  skip_confirmation: boolean;
};

export type MailcoachSubscribeData = {
  SUBSCRIBER_UUID: any;
  SUBSCRIBER_EMAIL: any;
  STATUS: string;
};

export type MailcoachUnsubscribeInputs = {
  SUBSCRIBER_UUID: string;
};

export type MailcoachUnsubscribeData = {
};

export type MailcoachUpdateCampaignInputs = {
  CAMPAIGN_UUID: string;
  name: string;
  subject: string;
  html: string;
  from_email: string;
  schedule_at: string;
};

export type MailcoachUpdateCampaignData = {
  CAMPAIGN_UUID: any;
  CAMPAIGN_NAME: any;
  STATUS: string;
};

export type MailcoachUpdateEmailListInputs = {
  LIST_UUID: string;
  name: string;
  default_from_email: string;
  default_from_name: string;
  default_reply_to_email: string;
  requires_confirmation: boolean;
};

export type MailcoachUpdateEmailListData = {
  LIST_UUID: any;
  LIST_NAME: any;
};

export type MailcoachUpdateSegmentInputs = {
  LIST_UUID: string;
  SEGMENT_UUID: string;
  name: string;
  positive_tags: string;
  negative_tags: string;
};

export type MailcoachUpdateSegmentData = {
  SEGMENT_UUID: any;
  SEGMENT_NAME: any;
};

export type MailcoachUpdateSubscriberImportInputs = {
  IMPORT_UUID: string;
  subscribers_csv: string;
  subscribe_unsubscribed: boolean;
  unsubscribe_others: boolean;
  replace_tags: boolean;
};

export type MailcoachUpdateSubscriberImportData = {
  IMPORT_UUID: any;
  STATUS: string;
};

export type MailcoachUpdateSubscriberInputs = {
  SUBSCRIBER_UUID: string;
  email: string;
  first_name: string;
  last_name: string;
  tags: string;
  append_tags: boolean;
};

export type MailcoachUpdateSubscriberData = {
  SUBSCRIBER_UUID: any;
  EMAIL: any;
  STATUS: string;
};

export type MailcoachUpdateTagInputs = {
  LIST_UUID: string;
  TAG_UUID: string;
  name: string;
  visible_in_preferences: boolean;
};

export type MailcoachUpdateTagData = {
  TAG_UUID: any;
  TAG_NAME: any;
};

export type MailcoachUpdateTemplateInputs = {
  TEMPLATE_UUID: string;
  name: string;
  html: string;
};

export type MailcoachUpdateTemplateData = {
  TEMPLATE_UUID: any;
  TEMPLATE_NAME: any;
};
