// This file is auto-generated by scripts/generate-warp-types.js

export type StripeCreateInvoiceInputs = {
  customer: string;
  collection_method: string;
  days_until_due: number;
  description: string;
};

export type StripeCreateInvoiceData = {
  INVOICE_ID: any;
  STATUS: string;
  HOSTED_URL: any;
};

export type StripeCreatePaymentLinkInputs = {
  price: string;
  quantity: number;
};

export type StripeCreatePaymentLinkData = {
  URL: any;
  ID: any;
};

export type StripeGetBalanceInputs = {
};

export type StripeGetBalanceData = {
  AVAILABLE: any;
  PENDING: any;
};

export type StripeGetCustomerInputs = {
  CUSTOMER_ID: string;
};

export type StripeGetCustomerData = {
  EMAIL: any;
  NAME: any;
  ID: any;
};

export type StripeListCustomersInputs = {
  limit: number;
  email: string;
};

export type StripeListCustomersData = {
  CUSTOMERS: any;
  HAS_MORE: boolean;
};

export type StripeListPaymentsInputs = {
  limit: number;
  customer: string;
};

export type StripeListPaymentsData = {
  PAYMENTS: any;
  HAS_MORE: boolean;
};

export type StripeListSubscriptionsInputs = {
  limit: number;
  customer: string;
  status: string;
};

export type StripeListSubscriptionsData = {
  SUBSCRIPTIONS: any;
  HAS_MORE: boolean;
};
