// This file is auto-generated by scripts/generate-warp-types.js

export type StripeGetCustomerInputs = {
  CUSTOMER_ID: string;
};

export type StripeGetCustomerData = {
  EMAIL: any;
  NAME: any;
  ID: any;
};
