// This file is auto-generated by scripts/generate-warp-types.js

export type xExchangeDevnetSwapXOXNOtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapXOXNOtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};
