// This file is auto-generated by scripts/generate-warp-types.js

export type xExchangeDevnetSwapASHtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapASHtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapBUSDtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapBUSDtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapCRTtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapCRTtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeSwapWEGLDtoMEXInputs = {
  asset: string;
};

export type xExchangeSwapWEGLDtoMEXData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapEMRtoUSDCInputs = {
  asset: string;
};

export type xExchangeDevnetSwapEMRtoUSDCData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapEMRtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapEMRtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapHTMtoUSDCInputs = {
  asset: string;
};

export type xExchangeDevnetSwapHTMtoUSDCData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapHTMtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapHTMtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapITHEUMtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapITHEUMtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapKWAKtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapKWAKtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapLEGLDtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapLEGLDtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapLXOXNOtoXOXNOInputs = {
  asset: string;
};

export type xExchangeDevnetSwapLXOXNOtoXOXNOData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapMEXtoUSDCInputs = {
  asset: string;
};

export type xExchangeDevnetSwapMEXtoUSDCData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapMEXtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapMEXtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapPROTEOtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapPROTEOtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapRIDEtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapRIDEtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapSUPERtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapSUPERtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapUSDCtoEMRInputs = {
  asset: string;
};

export type xExchangeDevnetSwapUSDCtoEMRData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapUSDCtoHTMInputs = {
  asset: string;
};

export type xExchangeDevnetSwapUSDCtoHTMData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapUSDCtoMEXInputs = {
  asset: string;
};

export type xExchangeDevnetSwapUSDCtoMEXData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapUSDCtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapUSDCtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapUSDTtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapUSDTtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapUTKtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapUTKtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWBTCtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWBTCtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoASHInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoASHData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoBUSDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoBUSDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoCRTInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoCRTData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoEMRInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoEMRData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoHTMInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoHTMData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoITHEUMInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoITHEUMData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoKWAKInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoKWAKData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoLEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoLEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoMEXInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoMEXData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoPROTEOInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoPROTEOData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoRIDEInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoRIDEData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoSUPERInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoSUPERData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoUSDCInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoUSDCData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoUSDTInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoUSDTData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoUTKInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoUTKData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoWBTCInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoWBTCData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoWETHInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoWETHData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWEGLDtoXOXNOInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWEGLDtoXOXNOData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapWETHtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapWETHtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapXOXNOtoLXOXNOInputs = {
  asset: string;
};

export type xExchangeDevnetSwapXOXNOtoLXOXNOData = {
  OUT: any;
  AMOUNT_OUT: any;
};

export type xExchangeDevnetSwapXOXNOtoWEGLDInputs = {
  asset: string;
};

export type xExchangeDevnetSwapXOXNOtoWEGLDData = {
  OUT: any;
  AMOUNT_OUT: any;
};
