// This file is auto-generated by scripts/generate-warp-types.js

export type MailgunSendEmailInputs = {
  AUTH_TOKEN: string;
  to: string;
  from: string;
  subject: string;
  text: string;
};

export type MailgunSendEmailData = {
  ID: any;
  MESSAGE: any;
};
