// This file is auto-generated by scripts/generate-warp-types.js

export type ShopBookingStatusInputs = {
};

export type ShopBookingStatusData = {
  BOOKING_ENABLED: any;
};

export type ShopToggleBookingInputs = {
  id: string;
  key: string;
  enabled: boolean;
};

export type ShopBrowseProductsInputs = {
  id: string;
};

export type ShopBrowseProductsData = {
  PRODUCTS: any;
};

export type ShopConfigureInputs = {
  id: string;
  category: string;
  location: string;
  description: string;
  image_url: string;
  website: string;
};

export type ShopPaymentInfoInputs = {
  id: string;
};

export type ShopPaymentInfoData = {
  CHAIN: any;
  ADDRESS: any;
  TOKEN: any;
};

export type ShopAddProductInputs = {
  id: string;
  product_slug: string;
  name: string;
  price: string;
  category: string;
  description: string;
};

export type ShopRemoveProductInputs = {
  id: string;
  product_slug: string;
};

export type ShopUpdateStockInputs = {
  id: string;
  product_slug: string;
  in_stock: string;
};

export type ShopProductsInputs = {
};

export type ShopProductsData = {
  PRODUCTS: any;
};

export type ShopRegisterInputs = {
  id: string;
  category: string;
  location: string;
  description: string;
  image_url: string;
  website: string;
};

export type ShopSearchInputs = {
  category: string;
  offset: number;
  limit: number;
};

export type ShopSearchData = {
  SHOPS: any;
};

export type ShopAddServiceInputs = {
  id: string;
  service_slug: string;
  name: string;
  price: string;
  duration_minutes: string;
  category: string;
  description: string;
};

export type ShopBookPayServiceInputs = {
  chain: string;
  receiver: string;
  asset: string;
};

export type ShopBookPayServiceData = {
  SERVICE_NAME: any;
  SERVICE_PRICE: number;
  SERVICE_DESCRIPTION: any;
  SERVICE_DURATION: any;
  PAY_CHAIN: any;
  PAY_ADDRESS: any;
  PAY_TOKEN: any;
};

export type ShopRemoveServiceInputs = {
  service_slug: string;
};

export type ShopServicesInputs = {
};

export type ShopServicesData = {
  SERVICES: any;
};

export type ShopSetPaymentDestinationInputs = {
  id: string;
  chain: string;
  address: string;
  token: string;
};
