// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXAccountInfoInputs = {
  ADDRESS: string;
};

export type MultiversXAccountInfoData = {
  ACCOUNT_DATA: any;
  BALANCE: string;
  BALANCE_EGLD: number;
  BALANCE_FORMATTED: string;
  NONCE: number;
  USERNAME: any;
};
