// This file is auto-generated by scripts/generate-warp-types.js

export type LemonSqueezyCreateCheckoutInputs = {
  store_id: string;
  variant_id: string;
  data_type: string;
  store_type: string;
  variant_type: string;
};

export type LemonSqueezyCreateCheckoutData = {
  CHECKOUT_URL: any;
  ID: any;
};

export type LemonSqueezyGetCustomerInputs = {
  CUSTOMER_ID: string;
};

export type LemonSqueezyGetCustomerData = {
  CUSTOMER: any;
  NAME: any;
  EMAIL: any;
};

export type LemonSqueezyListLicenseKeysInputs = {
  store_id: string;
};

export type LemonSqueezyListLicenseKeysData = {
  LICENSE_KEYS: any;
  COUNT: any;
};

export type LemonSqueezyListOrdersInputs = {
  store_id: string;
  status: string;
};

export type LemonSqueezyListOrdersData = {
  ORDERS: any;
  COUNT: any;
};

export type LemonSqueezyListProductsInputs = {
  store_id: string;
};

export type LemonSqueezyListProductsData = {
  PRODUCTS: any;
  COUNT: any;
};

export type LemonSqueezyListSubscriptionsInputs = {
  store_id: string;
  status: string;
};

export type LemonSqueezyListSubscriptionsData = {
  SUBSCRIPTIONS: any;
  COUNT: any;
};
