// This file is auto-generated by scripts/generate-warp-types.js

export type InquiryProductConfiguratorInputs = {
  name: string;
  email: string;
  phone: string;
  productSlug: string;
  quantity: number;
  color: string;
  text: string;
  variationSku: string;
  type: string;
  description: string;
  title: string;
  tags: string;
  contactIds: string;
};
