// This file is auto-generated by scripts/generate-warp-types.js

export type TrelloCreateCardInputs = {
  idList: string;
  name: string;
  desc: string;
};

export type TrelloCreateCardData = {
  CARD_ID: any;
  URL: any;
};

export type TrelloGetListsInputs = {
  BOARD_ID: string;
};

export type TrelloGetListsData = {
  LISTS: any;
};
