// This file is auto-generated by scripts/generate-warp-types.js

export type TrelloGetListsInputs = {
  BOARD_ID: string;
  key: string;
  token: string;
};

export type TrelloGetListsData = {
  LISTS: any;
};
