// This file is auto-generated by scripts/generate-warp-types.js

export type OutreachContactMessageInputs = {
  contactId: string;
  context: string;
  channel: string;
  integrationType: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type OutreachContactMessageData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type OutreachSegmentScanInputs = {
  tag: string;
  minInactiveDays: string;
};

export type OutreachSegmentScanData = {
  _DATA: any;
};
