// This file is auto-generated by scripts/generate-warp-types.js

export type OutreachAIDraftInputs = {
  contactId: string;
  occasion: string;
  context: string;
};

export type OutreachAIDraftData = {
  _DRAFT: any;
};

export type OutreachContactMessageInputs = {
  contactId: string;
  context: string;
  channel: string;
  integration: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type OutreachContactMessageData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type OutreachEnrollContactInputs = {
  contactId: string;
  outreach_sequence: string;
  key: string;
  outreach_step: string;
  tag: string;
};

export type OutreachExecuteStepInputs = {
  contactId: string;
  sequenceSlug: string;
  integration: string;
  recipientId: string;
  recipientName: string;
  message: string;
  value: string;
  key: string;
};

export type OutreachExecuteStepData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
  TEMPLATE_CONTENT: any;
  TEMPLATE_CHANNEL: any;
  TEMPLATE_SLUG: any;
  TEMPLATE_STEP: any;
};

export type OutreachHandleReplyInputs = {
  contactId: string;
  tag: string;
  type: string;
  description: string;
  outreach: boolean;
  event: string;
};

export type OutreachLogTouchInputs = {
  contactId: string;
  type: string;
  description: string;
  outreach: boolean;
  channel: string;
  templateId: string;
  variant: string;
  sequenceStep: string;
};

export type OutreachParkContactInputs = {
  contactId: string;
  tag: string;
};

export type OutreachScoreUpdateInputs = {
  contactId: string;
  value: string;
  key: string;
};

export type OutreachScoreUpdateData = {
  _SCORE: any;
};

export type OutreachSegmentScanInputs = {
  tag: string;
  lastActivityBefore: string;
};

export type OutreachSegmentScanData = {
  _DATA: any;
};

export type OutreachStatsInputs = {
  templateId: string;
  variant: string;
  channel: string;
  sinceDate: string;
  perPage: string;
};

export type OutreachCreateTemplateInputs = {
  title: string;
  content: string;
  slug: string;
  channel: string;
  step: string;
  delay_days: string;
  variables: string;
};
