// This file is auto-generated by scripts/generate-warp-types.js

export type OutreachContactMessageInputs = {
  contactId: string;
  context: string;
  channel: string;
  integrationType: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type OutreachContactMessageData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type OutreachLogTouchInputs = {
  contactId: string;
  type: string;
  description: string;
  outreach: boolean;
  channel: string;
  templateId: string;
  variant: string;
  sequenceStep: string;
};

export type OutreachSegmentScanInputs = {
  tag: string;
  minInactiveDays: string;
};

export type OutreachSegmentScanData = {
  _DATA: any;
};

export type OutreachStatsInputs = {
  templateId: string;
  variant: string;
  channel: string;
  sinceDate: string;
  perPage: string;
};
