// This file is auto-generated by scripts/generate-warp-types.js

export type ThreadsCreateTextPostInputs = {
  text: string;
  media_type: string;
  access_token: string;
};

export type ThreadsCreateTextPostData = {
  CONTAINER_ID: any;
};

export type ThreadsGetInsightsInputs = {
  metric: string;
  access_token: string;
};

export type ThreadsGetInsightsData = {
  INSIGHTS: any;
};

export type ThreadsGetProfileInputs = {
  fields: string;
  access_token: string;
};

export type ThreadsGetProfileData = {
  ID: any;
  USERNAME: any;
  BIO: any;
};

export type ThreadsPublishPostInputs = {
  creation_id: string;
  access_token: string;
};

export type ThreadsPublishPostData = {
  POST_ID: any;
};
