// This file is auto-generated by scripts/generate-warp-types.js

export type LinkedInCreatePostInputs = {
  author: string;
  text: string;
  visibility: string;
  shareMediaCategory: string;
  lifecycleState: string;
};

export type LinkedInCreatePostData = {
  POST_ID: any;
};
