// This file is auto-generated by scripts/generate-warp-types.js

export type PollTransferAdminInputs = {
};

export type PollDetailInputs = {
};

export type PollCreateGroupInputs = {
};

export type PollGetGroupPollsInputs = {
};

export type PollGetGroupInputs = {
};

export type PollCreateInviteInputs = {
};

export type PollJoinWithInviteInputs = {
};

export type PollRevokeInviteInputs = {
};

export type PollGetInviteInputs = {
};

export type PollApproveMemberInputs = {
};

export type PollIsMemberInputs = {
};

export type PollRemoveMemberInputs = {
};

export type PollGetMemberVoteInputs = {
};

export type PollGetMembersInputs = {
};

export type PollJoinSpaceInputs = {
};

export type PollCreatePollInputs = {
};

export type PollCreatePollData = {
  RESULT: any;
};

export type PollResultsInputs = {
};

export type PollActivePollsInputs = {
};

export type PollDenyRequestInputs = {
};

export type PollPendingRequestsInputs = {
};

export type PollHasVotedInputs = {
};

export type PollVoteTXInputs = {
};
