// This file is auto-generated by scripts/generate-warp-types.js

export type AnthropicAddFollowupInputs = {
  RUN_ID: string;
  FOLLOWUP: string;
  MODEL: string;
  MAX_TOKENS: number;
  ROLE: string;
};

export type AnthropicAddFollowupData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: string;
};

export type AnthropicCancelTaskInputs = {
  RUN_ID: string;
};

export type AnthropicCancelTaskData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: string;
};

export type AnthropicClaudeCodeAddFollowupInputs = {
  RUN_ID: string;
  FOLLOWUP: string;
};

export type AnthropicClaudeCodeAddFollowupData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type AnthropicClaudeCodeCancelTaskInputs = {
  RUN_ID: string;
};

export type AnthropicClaudeCodeCancelTaskData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type AnthropicClaudeCodeGetTaskStatusInputs = {
  RUN_ID: string;
};

export type AnthropicClaudeCodeGetTaskStatusData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type AnthropicClaudeCodeLaunchTaskInputs = {
  RUN_ID: string;
  TASK: string;
};

export type AnthropicClaudeCodeLaunchTaskData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type AnthropicGetTaskStatusInputs = {
  RUN_ID: string;
};

export type AnthropicGetTaskStatusData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: string;
};

export type AnthropicInstallJoAiPluginInputs = {
  PLUGIN_NAME: string;
};

export type AnthropicLaunchTaskInputs = {
  TASK: string;
  MODEL: string;
  MAX_TOKENS: number;
  CUSTOM_ID: string;
  ROLE: string;
};

export type AnthropicLaunchTaskData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: string;
};
