// This file is auto-generated by scripts/generate-warp-types.js

export type PassGenerateInputs = {
  source: string;
  reference: string;
  platform: string;
  fields: string;
};

export type PassGenerateData = {
  PASS_ID: any;
  PLATFORM: any;
  WALLET_URL: any;
};

export type PassUpdateInputs = {
  fields: string;
};

export type PassUpdateData = {
  PASS_ID: any;
};

export type PassVoidInputs = {
};
