// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleDocsCreateDocumentInputs = {
  title: string;
};

export type GoogleDocsCreateDocumentData = {
  DOCUMENT_ID: any;
  TITLE: any;
};

export type GoogleDocsGetDocumentInputs = {
  DOCUMENT_ID: string;
};

export type GoogleDocsGetDocumentData = {
  TITLE: any;
  BODY: any;
};
