// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleDocsGetDocumentInputs = {
  DOCUMENT_ID: string;
};

export type GoogleDocsGetDocumentData = {
  TITLE: any;
  BODY: any;
};
