// This file is auto-generated by scripts/generate-warp-types.js

export type xMoneyPaymentLinkCreateInputs = {
  type: string;
  reference: string;
  total: string;
  currency: string;
  return_url: string;
  email: string;
  country: string;
};

export type xMoneyPaymentLinkCreateData = {
  LINK: any;
};
