pub const ERR_CODE_EMPTY: &str = "coupon code cannot be empty";
pub const ERR_CODE_TOO_LONG: &str = "coupon code must be 32 bytes or fewer";
pub const ERR_CODE_TAKEN: &str = "coupon code already exists";
pub const ERR_COUPON_NOT_FOUND: &str = "coupon not found";
pub const ERR_COUPON_REVOKED: &str = "coupon has been revoked";
pub const ERR_COUPON_EXPIRED: &str = "coupon has expired";
pub const ERR_COUPON_FULLY_USED: &str = "coupon has reached its usage limit";
pub const ERR_NOT_OWNER: &str = "only the coupon owner can perform this action";
pub const ERR_INVALID_DISCOUNT: &str = "discount_percent must be between 1 and 100";
