// This file is auto-generated by scripts/generate-warp-types.js

export type PerplexitySearchInputs = {
  model: string;
  messages: string;
};

export type PerplexitySearchData = {
  CONTENT: any;
  CITATIONS: any;
};
