// This file is auto-generated by scripts/generate-warp-types.js

export type xAllianceProjectCheckinInputs = {
  report: string;
};

export type xAllianceExperienceAddPointsInputs = {
};

export type xAllianceExperienceDAOMembersInputs = {
};

export type xAllianceExperienceMemberPointsInputs = {
};

export type xAllianceExperienceMemberPointsData = {
  POINTS: any;
};

export type xAllianceExperienceRemovePointsInputs = {
};

export type xAllianceExperienceAddTierInputs = {
};

export type xAllianceExperienceClearTiersInputs = {
};
