// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    signature
    (
        init => init
        upgrade => upgrade
        createRequest => create_request
        sign => sign
        cancelRequest => cancel_request
        expireRequest => expire_request
        getRequest => get_request
        getRequestSigners => get_request_signers
        getSignedBy => get_signed_by
        hasSigned => has_signed
        isEligibleSigner => is_eligible_signer
        getRequestsByCreator => get_requests_by_creator
        getNextRequestId => get_next_request_id
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
