// This file is auto-generated by scripts/generate-warp-types.js

export type ReviewStarRatingInputs = {
  rating: string;
  name: string;
  phone: string;
};

export type ReviewStarRatingData = {
  RATING: any;
  NAME: any;
  PHONE: any;
};
