// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXTransactionStatusInputs = {
  TX_HASH: string;
};

export type MultiversXTransactionStatusData = {
  STATUS: string;
  TX_HASH: string;
  SENDER: string;
  RECEIVER: string;
  VALUE: string;
  GAS_USED: number;
  FEE: string;
  MINI_BLOCK_HASH: string;
  TIMESTAMP: number;
  IS_COMPLETED: boolean;
  IS_PENDING: boolean;
  IS_SUCCESS: boolean;
  IS_FAILED: boolean;
};
