// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           22
// Async Callback (empty):               1
// Total number of exported functions:  25

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    poll
    (
        init => init
        upgrade => upgrade
        createGroup => create_group
        transferAdmin => transfer_admin
        createInvite => create_invite
        revokeInvite => revoke_invite
        joinWithInvite => join_with_invite
        requestMembership => request_membership
        approveMember => approve_member
        denyRequest => deny_request
        removeMember => remove_member
        createPoll => create_poll
        vote => vote
        getGroup => get_group
        getMembers => get_members
        getPendingRequests => get_pending_requests
        getInvite => get_invite
        getPoll => get_poll
        getPollResults => get_poll_results
        getGroupPolls => get_group_polls
        getActivePolls => get_active_polls
        isMember => is_member
        hasVoted => has_voted
        getMemberVote => get_member_vote
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
