// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXStakingClaimRewardsInputs = {
  PROVIDER: string;
};

export type MultiversXStakingClaimRewardsData = {
  TX_HASH: string;
  PROVIDER: any;
  REWARDS_CLAIMED_EGLD: number;
};
