// This file is auto-generated by scripts/generate-warp-types.js

export type BrowserClickElementInputs = {
  uid: string;
};

export type BrowserEvaluateScriptInputs = {
  expression: string;
};

export type BrowserFillFormInputs = {
  ELEMENTS: string;
};

export type BrowserGetPageContentInputs = {
};

export type BrowserListConsoleMessagesInputs = {
};

export type BrowserListNetworkRequestsInputs = {
};

export type BrowserNavigateInputs = {
  url: string;
};

export type BrowserScreenshotInputs = {
};
