// This file is auto-generated by scripts/generate-warp-types.js

export type SignatureCancelInputs = {
  requestId: string;
};

export type SignatureCancelData = {
  REQUEST_TITLE: any;
  DOCUMENT_HASH: string;
};

export type SignatureCreateInputs = {
  title: string;
  documentHash: string;
  document: string;
  deadlineHours: string;
  signerEmail: string;
  signerName: string;
};

export type SignatureCreateData = {
  REQUEST_ID: any;
};

export type SignatureDeclineInputs = {
  requestId: string;
  creatorEmail: string;
};

export type SignatureDeclineData = {
  REQUEST_TITLE: any;
  DOCUMENT_HASH: string;
};

export type SignatureListInputs = {
};

export type SignatureListData = {
  REQUESTS: any;
};

export type SignatureRemindInputs = {
  requestId: string;
  signerEmail: string;
  signerName: string;
  signerAddress: string;
  teamSlug: string;
};

export type SignatureRemindData = {
  REQUEST_TITLE: any;
  DOCUMENT_HASH: string;
};

export type SignatureSelfSignInputs = {
  title: string;
  documentHash: string;
  document: string;
  recipientEmail: string;
  recipientName: string;
};

export type SignatureSelfSignData = {
  REQUEST_ID: any;
};

export type SignatureSignInputs = {
  requestId: string;
};

export type SignatureSignData = {
  REQUEST_TITLE: any;
  DOCUMENT_HASH: string;
};

export type SignatureViewInputs = {
  requestId: string;
};

export type SignatureViewData = {
  TITLE: any;
  CREATOR: any;
  DOCUMENT_HASH: string;
  SIGNER_COUNT: number;
  SIGNED_COUNT: number;
  STATUS: string;
};
