// This file is auto-generated by scripts/generate-warp-types.js

export type MediumCreatePostInputs = {
  USER_ID: string;
  title: string;
  content: string;
  contentFormat: string;
  publishStatus: string;
  tags: string;
};

export type MediumCreatePostData = {
  POST_ID: any;
  TITLE: any;
  URL: any;
};

export type MediumGetUserInputs = {
};

export type MediumGetUserData = {
  ID: any;
  USERNAME: any;
  NAME: any;
  URL: any;
};
