// This file is auto-generated by scripts/generate-warp-types.js

export type AsanaCreateTaskInputs = {
  name: string;
  notes: string;
  projects: string;
  workspace: string;
};

export type AsanaCreateTaskData = {
  TASK_ID: any;
  PERMALINK: any;
};

export type AsanaGetTasksInputs = {
  project: string;
  limit: number;
  opt_fields: string;
};

export type AsanaGetTasksData = {
  TASKS: any;
  COUNT: any;
};
