// This file is auto-generated by scripts/generate-warp-types.js

export type AsanaGetTasksInputs = {
  project: string;
  limit: number;
  opt_fields: string;
};

export type AsanaGetTasksData = {
  TASKS: any;
  COUNT: any;
};
