// This file is auto-generated by scripts/generate-warp-types.js

export type LaravelCloudGetCommandInputs = {
  COMMAND_ID: string;
};

export type LaravelCloudGetCommandData = {
  COMMAND: any;
  STATUS: string;
  FINISHED_AT: any;
};

export type LaravelCloudInitiateDeploymentInputs = {
  ENVIRONMENT_ID: string;
  BRANCH: string;
  COMMIT: string;
};

export type LaravelCloudInitiateDeploymentData = {
  ID: any;
  STATUS: string;
};

export type LaravelCloudListApplicationsInputs = {
};

export type LaravelCloudListApplicationsData = {
  COUNT: number;
  APPLICATIONS: string[];
};

export type LaravelCloudListEnvironmentsInputs = {
  APPLICATION_ID: string;
};

export type LaravelCloudListEnvironmentsData = {
  COUNT: number;
  ENVIRONMENTS: string[];
};

export type LaravelCloudRunCommandInputs = {
  ENVIRONMENT_ID: string;
  COMMAND: string;
};

export type LaravelCloudRunCommandData = {
  ID: any;
  STATUS: string;
};
