// This file is auto-generated by scripts/generate-warp-types.js

export type FormCreateInputs = {
  title: string;
  description: string;
  PAYLOAD: string;
};

export type FormCreateData = {
  FORM_ID: any;
  FORM_URL: any;
};

export type FormAddFieldInputs = {
  fieldName: string;
  fieldType: string;
  required: string;
  currentDefinition: string;
  formId: string;
  PAYLOAD: string;
};

export type FormRemoveFieldInputs = {
  fieldKey: string;
  currentDefinition: string;
  formId: string;
  PAYLOAD: string;
};

export type FormUpdateFieldInputs = {
  fieldKey: string;
  changes: string;
  currentDefinition: string;
  formId: string;
  PAYLOAD: string;
};

export type FormGetInputs = {
  formId: string;
};

export type FormListInputs = {
};
