// This file is auto-generated by scripts/generate-warp-types.js

export type FormCreateInputs = {
  definition: string;
  store: boolean;
  optIn: boolean;
  agent: string;
  public: boolean;
  extras: string;
  form: boolean;
};

export type FormCreateData = {
  FORM_ID: any;
  FORM_URL: any;
  FORM: any;
};

export type FormDeleteInputs = {
  formId: string;
};

export type FormAddFieldInputs = {
  fieldName: string;
  fieldType: string;
  required: string;
  currentDefinition: string;
  formId: string;
  PAYLOAD: string;
};

export type FormRemoveFieldInputs = {
  fieldKey: string;
  currentDefinition: string;
  formId: string;
  PAYLOAD: string;
};

export type FormUpdateFieldInputs = {
  fieldKey: string;
  changes: string;
  currentDefinition: string;
  formId: string;
  PAYLOAD: string;
};

export type FormGetInputs = {
  formId: string;
};

export type FormGetData = {
  FORM: any;
};

export type FormInstallInputs = {
  formId: string;
};

export type FormInstallData = {
  FORM_ID: any;
  FORM_URL: any;
  FORM: any;
};

export type FormListInputs = {
};

export type FormListData = {
  FORMS: any;
};

export type FormPublishInputs = {
  formId: string;
  public: boolean;
  store: boolean;
};

export type FormPublishData = {
  FORM: any;
};

export type FormClearSubmissionsInputs = {
  formId: string;
  team: string;
};

export type FormDeleteSubmissionInputs = {
  formId: string;
  executionId: string;
  team: string;
};

export type FormSubmissionsInputs = {
  formId: string;
  page: string;
  perPage: string;
  team: string;
};

export type FormSubmissionsData = {
  SUBMISSIONS: any;
  COUNT: any;
};

export type FormUnpublishInputs = {
  formId: string;
  store: boolean;
};

export type FormUnpublishData = {
  FORM: any;
};

export type FormUpdateInputs = {
  formId: string;
  name: string;
  title: string;
  description: string;
  definition: string;
  store: boolean;
  public: boolean;
  optIn: boolean;
  extras: string;
};

export type FormUpdateData = {
  FORM: any;
};
