// This file is auto-generated by scripts/generate-warp-types.js

export type LaravelCloudListDeploymentsInputs = {
  ENVIRONMENT_ID: string;
};

export type LaravelCloudListDeploymentsData = {
  COUNT: number;
  DEPLOYMENTS: any[];
};
