// This file is auto-generated by scripts/generate-warp-types.js

export type IntercomCreateContactInputs = {
  email: string;
  name: string;
  role: string;
};

export type IntercomCreateContactData = {
  CONTACT_ID: any;
  EMAIL: any;
  NAME: any;
};

export type IntercomCreateConversationInputs = {
  userId: string;
  email: string;
  type: string;
  body: string;
};

export type IntercomCreateConversationData = {
  CONVERSATION_ID: any;
};
