// This file is auto-generated by scripts/generate-warp-types.js

export type IntercomCreateConversationInputs = {
  userId: string;
  email: string;
  type: string;
  body: string;
};

export type IntercomCreateConversationData = {
  CONVERSATION_ID: any;
};
