// This file is auto-generated by scripts/generate-warp-types.js

export type JoAiCampaignStatsInputs = {
  team: string;
};

export type JoAiCampaignStatsData = {
  TOTAL_CAMPAIGNS: any;
  DRAFT_CAMPAIGNS: any;
  TOTAL_SENT: any;
};
