// This file is auto-generated by scripts/generate-warp-types.js

export type OpenAIAddFollowupInputs = {
  RUN_ID: string;
  FOLLOWUP: string;
  MODEL: string;
  BACKGROUND: boolean;
};

export type OpenAIAddFollowupData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type OpenAICancelTaskInputs = {
  RUN_ID: string;
};

export type OpenAICancelTaskData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type OpenAICodexCLIAddFollowupInputs = {
  RUN_ID: string;
  FOLLOWUP: string;
};

export type OpenAICodexCLIAddFollowupData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type OpenAICodexCLICancelTaskInputs = {
  RUN_ID: string;
};

export type OpenAICodexCLICancelTaskData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type OpenAICodexCLIGetTaskStatusInputs = {
  RUN_ID: string;
};

export type OpenAICodexCLIGetTaskStatusData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type OpenAICodexCLILaunchTaskInputs = {
  RUN_ID: string;
  TASK: string;
};

export type OpenAICodexCLILaunchTaskData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type OpenAIGetTaskStatusInputs = {
  RUN_ID: string;
};

export type OpenAIGetTaskStatusData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type OpenAIConnectJoAiAppInputs = {
  MCP_URL: string;
};

export type OpenAIInstallJoAiPluginInputs = {
  PLUGIN_NAME: string;
};

export type OpenAILaunchTaskInputs = {
  TASK: string;
  MODEL: string;
  BACKGROUND: boolean;
};

export type OpenAILaunchTaskData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};
