// This file is auto-generated by scripts/generate-warp-types.js

export type GitHubAddCommenttoIssueInputs = {
  OWNER: string;
  REPO: string;
  ISSUE_NUMBER: number;
  body: string;
};

export type GitHubAddCommenttoIssueData = {
  COMMENT_ID: any;
  COMMENT_URL: any;
};

export type GitHubCreateIssueInputs = {
  OWNER: string;
  REPO: string;
  title: string;
  body: string;
  labels: string;
  assignees: string;
};

export type GitHubCreateIssueData = {
  ISSUE_NUMBER: any;
  ISSUE_URL: any;
  ISSUE_ID: any;
};

export type GitHubCreatePullRequestInputs = {
  OWNER: string;
  REPO: string;
  title: string;
  body: string;
  head: string;
  base: string;
  draft: boolean;
};

export type GitHubCreatePullRequestData = {
  PR_NUMBER: any;
  PR_URL: any;
  PR_ID: any;
  STATE: any;
};

export type GitHubGetIssueInputs = {
  OWNER: string;
  REPO: string;
  ISSUE_NUMBER: number;
};

export type GitHubGetIssueData = {
  NUMBER: any;
  TITLE: any;
  BODY: any;
  STATE: any;
  URL: any;
  LABELS: any;
  ASSIGNEES: any;
  AUTHOR: any;
};

export type GitHubGetRepositoryInputs = {
  OWNER: string;
  REPO: string;
};

export type GitHubGetRepositoryData = {
  NAME: any;
  FULL_NAME: any;
  DESCRIPTION: any;
  STARS: any;
  FORKS: any;
  LANGUAGE: any;
  URL: any;
  CLONE_URL: any;
};

export type GitHubListIssuesInputs = {
  OWNER: string;
  REPO: string;
  state: string;
  labels: string;
  assignee: string;
  per_page: number;
};

export type GitHubListIssuesData = {
  COUNT: number;
};

export type GitHubSearchRepositoriesInputs = {
  q: string;
  sort: string;
  order: string;
  per_page: number;
};

export type GitHubSearchRepositoriesData = {
  REPOSITORIES: any;
  TOTAL_COUNT: number;
};
