// This file is auto-generated by scripts/generate-warp-types.js

export type GitHubSearchRepositoriesInputs = {
  q: string;
  sort: string;
  order: string;
  per_page: number;
};

export type GitHubSearchRepositoriesData = {
  REPOSITORIES: any;
  TOTAL_COUNT: number;
};
