// This file is auto-generated by scripts/generate-warp-types.js

export type JoAiOnboardingBusinessInfoInputs = {
  companyName: string;
  companyWebsite: string;
  teamSize: string;
  annualRevenue: string;
  role: string;
};
