// This file is auto-generated by scripts/generate-warp-types.js

export type ElevenLabsListVoicesInputs = {
};

export type ElevenLabsListVoicesData = {
  VOICES: any;
  COUNT: any;
};

export type ElevenLabsSpeechtoTextInputs = {
  audio_url: string;
  language_code: string;
};

export type ElevenLabsSpeechtoTextData = {
  TEXT: any;
  LANGUAGE: any;
};

export type ElevenLabsTexttoSpeechInputs = {
  VOICE_ID: string;
  text: string;
  model_id: string;
  output_format: string;
  stability: number;
  similarity_boost: number;
  speed: number;
};
