// This file is auto-generated by scripts/generate-warp-types.js

export type TallyGetResponsesInputs = {
  FORM_ID: string;
};

export type TallyGetResponsesData = {
  RESPONSES: any;
  COUNT: any;
};

export type TallyListFormsInputs = {
};

export type TallyListFormsData = {
  FORMS: any;
  COUNT: any;
};
