// This file is auto-generated by scripts/generate-warp-types.js

export type GitLabListProjectsInputs = {
  per_page: number;
  owned: boolean;
  search: string;
};

export type GitLabListProjectsData = {
  PROJECTS: any;
};
