// This file is auto-generated by scripts/generate-warp-types.js

export type GitLabCreateIssueInputs = {
  PROJECT_ID: string;
  title: string;
  description: string;
};

export type GitLabCreateIssueData = {
  ISSUE_ID: any;
  WEB_URL: any;
  TITLE: any;
};

export type GitLabListProjectsInputs = {
  per_page: number;
  owned: boolean;
  search: string;
};

export type GitLabListProjectsData = {
  PROJECTS: any;
};
