// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleTasksCreateTaskInputs = {
  TASKLIST_ID: string;
  title: string;
  notes: string;
  due: string;
};

export type GoogleTasksCreateTaskData = {
  TASK_ID: any;
  TITLE: any;
};

export type GoogleTasksListTasklistsInputs = {
  maxResults: number;
};

export type GoogleTasksListTasklistsData = {
  TASKLISTS: any;
};
