// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleTasksListTasklistsInputs = {
  maxResults: number;
};

export type GoogleTasksListTasklistsData = {
  TASKLISTS: any;
};
