// This file is auto-generated by scripts/generate-warp-types.js

export type SupabaseCallRPCFunctionInputs = {
  FUNCTION_NAME: string;
  args: string;
};

export type SupabaseCallRPCFunctionData = {
  RESULT: any;
};

export type SupabaseDeleteRowsInputs = {
  TABLE: string;
  FILTER: string;
};

export type SupabaseDeleteRowsData = {
  ROWS: any;
  COUNT: any;
};

export type SupabaseInsertRowsInputs = {
  TABLE: string;
  data: string;
};

export type SupabaseInsertRowsData = {
  ROWS: any;
  COUNT: any;
};

export type SupabaseQueryRowsInputs = {
  TABLE: string;
  select: string;
  filter: string;
  order: string;
  limit: number;
};

export type SupabaseQueryRowsData = {
  ROWS: any;
  COUNT: any;
};

export type SupabaseUpdateRowsInputs = {
  TABLE: string;
  FILTER: string;
  data: string;
};

export type SupabaseUpdateRowsData = {
  ROWS: any;
  COUNT: any;
};
