// This file is auto-generated by scripts/generate-warp-types.js

export type CalendlyListScheduledEventsInputs = {
  user: string;
  status: string;
  count: number;
};

export type CalendlyListScheduledEventsData = {
  EVENTS: any;
  COUNT: any;
};
