// This file is auto-generated by scripts/generate-warp-types.js

export type CalendlyListEventTypesInputs = {
  user: string;
  organization: string;
  count: number;
};

export type CalendlyListEventTypesData = {
  EVENT_TYPES: any;
  COUNT: any;
};

export type CalendlyListScheduledEventsInputs = {
  user: string;
  status: string;
  count: number;
};

export type CalendlyListScheduledEventsData = {
  EVENTS: any;
  COUNT: any;
};
