// This file is auto-generated by scripts/generate-warp-types.js

export type GeminiAddFollowupInputs = {
  MODEL: string;
  RUN_ID: string;
  FOLLOWUP: string;
};

export type GeminiAddFollowupData = {
  RUN_ID: any;
  RUN_STATUS: string;
  SUMMARY: any;
};

export type GeminiCancelTaskInputs = {
  RUN_ID: string;
};

export type GeminiCancelTaskData = {
  RUN_ID: any;
  RUN_STATUS: any;
  SUMMARY: any;
};

export type GeminiGetTaskStatusInputs = {
  RUN_ID: string;
};

export type GeminiGetTaskStatusData = {
  RUN_ID: any;
  RUN_STATUS: string;
  SUMMARY: any;
};

export type GeminiLaunchTaskInputs = {
  MODEL: string;
  TASK: string;
};

export type GeminiLaunchTaskData = {
  RUN_ID: any;
  RUN_STATUS: string;
  SUMMARY: any;
};
