// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXTransactionDetailsInputs = {
  TX_HASH: string;
};

export type MultiversXTransactionDetailsData = {
  TX_DATA: any;
  STATUS: string;
  TX_HASH: string;
  SENDER: string;
  RECEIVER: string;
  VALUE: string;
  VALUE_EGLD: number;
  VALUE_FORMATTED: string;
  GAS_PRICE: number;
  GAS_LIMIT: number;
  GAS_USED: number;
  FEE: string;
  FEE_EGLD: number;
  TIMESTAMP: number;
  NONCE: number;
  ROUND: number;
  DATA: string;
  SMART_CONTRACT_RESULTS: string[];
  FUNCTION: string;
  IS_SC_CALL: boolean;
};
