// This file is auto-generated by scripts/generate-warp-types.js

export type PeerMeMultiSigUnsignActionInputs = {
  ACTION_ID: number;
};

export type PeerMeMultiSigUnsignActionData = {
  SUCCESS: any;
};
