// This file is auto-generated by scripts/generate-warp-types.js

export type PeerMeEarnClaimSUPERRewardsInputs = {
};

export type PeerMeEarnDistributeColombiaStakingInputs = {
  ENTITY: string;
};

export type PeerMeEarnDistributePeerMeDAOInputs = {
};

export type PeerMeEarnGetEntityUsersInputs = {
  entity: string;
};

export type PeerMeEarnStakeSUPERInputs = {
};

export type PeerMeEarnWithdrawSUPERInputs = {
};

export type PeerMeIdentityBurnforTrustInputs = {
};

export type PeerMeMultiSigCheckSignedInputs = {
  multisig: string;
  USER_ADDRESS: string;
  ACTION_ID: string;
};

export type PeerMeMultiSigCheckSignedData = {
  SIGNED: any;
  HAS_SIGNED: boolean;
  STATUS: string;
};

export type PeerMeMultiSigCheckUserRoleInputs = {
  multisig: string;
  USER_ADDRESS: string;
};

export type PeerMeMultiSigCheckUserRoleData = {
  ROLE: any;
  ROLE_NAME: number;
  CAN_PROPOSE: number;
  CAN_SIGN: number;
};

export type PeerMeMultiSigDepositInputs = {
  multisig: string;
  AMOUNT: string;
};

export type PeerMeMultiSigDepositData = {
  SUCCESS: any;
};

export type PeerMeMultiSigDiscardActionInputs = {
  multisig: string;
  ACTION_ID: string;
};

export type PeerMeMultiSigDiscardActionData = {
  SUCCESS: any;
};

export type PeerMeMultiSigGetActionDetailsInputs = {
  multisig: string;
  ACTION_ID: string;
};

export type PeerMeMultiSigGetActionDetailsData = {
  ACTION_DATA: any;
  SIGNERS: any;
  SIGNER_COUNT: number;
  VALID_SIGNER_COUNT: number;
  QUORUM_REACHED: any;
  SIGNER_COUNT_NUMBER: number;
  VALID_SIGNER_COUNT_NUMBER: number;
  STATUS: string;
};

export type PeerMeMultiSigGetActionLastIndexInputs = {
  multisig: string;
};

export type PeerMeMultiSigGetActionLastIndexData = {
  LAST_INDEX: any;
  LAST_INDEX_NUMBER: number;
  TOTAL_PROPOSALS: any;
};

export type PeerMeMultiSigGetBoardMembersInputs = {
  multisig: string;
};

export type PeerMeMultiSigGetBoardMembersData = {
  BOARD_MEMBERS: any;
  COUNT: any;
  COUNT_NUMBER: number;
  MEMBERS_LIST: any;
};

export type PeerMeMultiSigGetPendingActionsInputs = {
  multisig: string;
};

export type PeerMeMultiSigGetPendingActionsData = {
  PENDING_ACTIONS: any;
  COUNT: number;
  COUNT_FORMATTED: string;
};

export type PeerMeMultiSigGetProposersInputs = {
  multisig: string;
};

export type PeerMeMultiSigGetProposersData = {
  PROPOSERS: any;
  COUNT: any;
  COUNT_NUMBER: number;
  PROPOSERS_LIST: any;
};

export type PeerMeMultiSigGetQuorumInputs = {
  multisig: string;
};

export type PeerMeMultiSigGetQuorumData = {
  QUORUM: any;
  QUORUM_NUMBER: number;
};

export type PeerMeMultiSigOverviewInputs = {
  multisig: string;
};

export type PeerMeMultiSigOverviewData = {
  QUORUM: any;
  BOARD_MEMBERS: any;
  PENDING: any;
  ROLE: any;
  QUORUM_NUM: number;
  MEMBERS_NUM: number;
  PENDING_COUNT: number;
  ROLE_NAME: number;
};

export type PeerMeMultiSigPerformActionInputs = {
  multisig: string;
  ACTION_ID: string;
};

export type PeerMeMultiSigPerformActionData = {
  RESULT: any;
  DEPLOYED_ADDRESS: any;
};

export type PeerMeMultiSigProposeAddBoardMemberInputs = {
  multisig: string;
  BOARD_MEMBER_ADDRESS: string;
};

export type PeerMeMultiSigProposeAddBoardMemberData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
};

export type PeerMeMultiSigProposeAddModuleInputs = {
  multisig: string;
  SC_ADDRESS: string;
};

export type PeerMeMultiSigProposeAddModuleData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
};

export type PeerMeMultiSigProposeAddProposerInputs = {
  multisig: string;
  PROPOSER_ADDRESS: string;
};

export type PeerMeMultiSigProposeAddProposerData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
};

export type PeerMeMultiSigProposeAsyncCallInputs = {
  multisig: string;
  TO_ADDRESS: string;
  EGLD_AMOUNT: string;
  GAS_LIMIT: number;
  FUNCTION_CALL: string;
};

export type PeerMeMultiSigProposeAsyncCallData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
};

export type PeerMeMultiSigProposeChangeQuorumInputs = {
  multisig: string;
  NEW_QUORUM: number;
};

export type PeerMeMultiSigProposeChangeQuorumData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
};

export type PeerMeMultiSigProposeRemoveModuleInputs = {
  multisig: string;
  SC_ADDRESS: string;
};

export type PeerMeMultiSigProposeRemoveModuleData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
};

export type PeerMeMultiSigProposeRemoveUserInputs = {
  multisig: string;
  USER_ADDRESS: string;
};

export type PeerMeMultiSigProposeRemoveUserData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
};

export type PeerMeMultiSigProposeSCDeployInputs = {
  multisig: string;
  AMOUNT: string;
  SOURCE_ADDRESS: string;
  CODE_METADATA: string;
  ARGUMENTS: string;
};

export type PeerMeMultiSigProposeSCDeployData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
};

export type PeerMeMultiSigProposeSCUpgradeInputs = {
  multisig: string;
  SC_ADDRESS: string;
  AMOUNT: string;
  SOURCE_ADDRESS: string;
  CODE_METADATA: string;
  ARGUMENTS: string;
};

export type PeerMeMultiSigProposeSCUpgradeData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
};

export type PeerMeMultiSigProposeSyncCallInputs = {
  multisig: string;
  TO_ADDRESS: string;
  EGLD_AMOUNT: string;
  GAS_LIMIT: number;
  FUNCTION_CALL: string;
};

export type PeerMeMultiSigProposeSyncCallData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
};

export type PeerMeMultiSigProposeTransferExecuteEGLDInputs = {
  multisig: string;
  TO_ADDRESS: string;
  EGLD_AMOUNT: string;
  GAS_LIMIT: number;
  FUNCTION_CALL: string;
};

export type PeerMeMultiSigProposeTransferExecuteEGLDData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
  EGLD_AMOUNT_FORMATTED: number;
};

export type PeerMeMultiSigProposeTransferExecuteESDTInputs = {
  multisig: string;
  TO_ADDRESS: string;
  TOKENS: string;
  GAS_LIMIT: number;
  FUNCTION_CALL: string;
};

export type PeerMeMultiSigProposeTransferExecuteESDTData = {
  ACTION_ID: any;
  ACTION_ID_NUMBER: number;
};

export type PeerMeMultiSigMyMultiSigsInputs = {
};

export type PeerMeMultiSigMyMultiSigsData = {
  MULTISIGS: any;
  COUNT: number;
};

export type PeerMeMultiSigRegisterMultiSigInputs = {
  MULTISIG_ADDRESS: string;
  NAME: string;
};

export type PeerMeMultiSigRenameMultiSigInputs = {
  MULTISIG_ADDRESS: string;
  NEW_NAME: string;
};

export type PeerMeMultiSigSignActionInputs = {
  multisig: string;
  ACTION_ID: string;
};

export type PeerMeMultiSigSignActionData = {
  SUCCESS: any;
};

export type PeerMeMultiSigSignandPerformInputs = {
  multisig: string;
  ACTION_ID: string;
};

export type PeerMeMultiSigSignandPerformData = {
  RESULT: any;
  DEPLOYED_ADDRESS: any;
};

export type PeerMeMultiSigUnsignActionInputs = {
  multisig: string;
  ACTION_ID: string;
};

export type PeerMeMultiSigUnsignActionData = {
  SUCCESS: any;
};
