// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXSetNFTCreateRoleInputs = {
  COLLECTION_ID: string;
  ADDRESS: string;
};

export type MultiversXSetNFTCreateRoleData = {
  TX_HASH: string;
  COLLECTION_ID: any;
};
