// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXTokenDetailsInputs = {
  TOKEN_IDENTIFIER: string;
};

export type MultiversXTokenDetailsData = {
  TOKEN_DATA: any;
  IDENTIFIER: string;
  NAME: string;
  TICKER: string;
  DECIMALS: number;
  SUPPLY: string;
  SUPPLY_FORMATTED: string;
  OWNER: string;
  ISSUER: string;
  TYPE: string;
  PRICE: any;
};
