// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleCalendarUpdateEventInputs = {
  calendarId: string;
  eventId: string;
  summary: string;
  description: string;
  startDateTime: string;
  endDateTime: string;
  startTimeZone: string;
  endTimeZone: string;
  location: string;
  attendees: string;
};

export type GoogleCalendarUpdateEventData = {
  EVENT_ID: any;
  EVENT_LINK: any;
};
