// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleMeetCreateMeetingInputs = {
  summary: string;
  startDateTime: string;
  endDateTime: string;
  requestId: string;
  conferenceSolutionKey: string;
};

export type GoogleMeetCreateMeetingData = {
  MEET_LINK: any;
  EVENT_ID: any;
  HTML_LINK: any;
};
