// This file is auto-generated by scripts/generate-warp-types.js

export type CouponViewInputs = {
  code: string;
};

export type CouponViewData = {
  COUPON_ID: any;
  COLLECTION_ID: any;
  DISCOUNT: any;
  MAX_USES: any;
  USED_COUNT: number;
  EXPIRES_AT: any;
  CREATED_AT: any;
  STATUS: string;
};
