// This file is auto-generated by scripts/generate-warp-types.js

export type RatingConfigureInputs = {
  promptText: string;
  reviewUrl: string;
};

export type RatingConfigureData = {
  PROMPT_TEXT: any;
  REVIEW_URL: any;
};
