// This file is auto-generated by scripts/generate-warp-types.js

export type ReadwiseGetDocumentInputs = {
  DOCUMENT_ID: string;
};

export type ReadwiseGetDocumentData = {
  TITLE: any;
  URL: any;
  CATEGORY: any;
  LOCATION: any;
};

export type ReadwiseListDocumentsInputs = {
  updatedAfter: string;
  location: string;
  category: string;
  tag: string;
  withHtmlContent: boolean;
  pageCursor: string;
  page_size: number;
};

export type ReadwiseListDocumentsData = {
  RESULTS: any;
  COUNT: number;
  NEXT_PAGE_CURSOR: any;
};

export type ReadwiseListTagsInputs = {
};

export type ReadwiseListTagsData = {
  TAGS: any;
  COUNT: number;
};
