// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleContactsSearchContactsInputs = {
  query: string;
  readMask: string;
};

export type GoogleContactsSearchContactsData = {
  RESULTS: any;
};
