// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleContactsCreateContactInputs = {
  givenName: string;
  familyName: string;
  email: string;
};

export type GoogleContactsCreateContactData = {
  RESOURCE_NAME: any;
  NAME: any;
};

export type GoogleContactsSearchContactsInputs = {
  query: string;
  readMask: string;
};

export type GoogleContactsSearchContactsData = {
  RESULTS: any;
};
