// This file is auto-generated by scripts/generate-warp-types.js

export type UpsellsAfterVisitInputs = {
  contactId: string;
  serviceCompleted: string;
  integrationType: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type UpsellsAfterVisitData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type UpsellsBundleSuggestInputs = {
  contactId: string;
  services: string;
  integrationType: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type UpsellsBundleSuggestData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type UpsellsProductAlertInputs = {
  contactId: string;
  productName: string;
  reason: string;
  integrationType: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type UpsellsProductAlertData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type UpsellsRecommendInputs = {
  contactId: string;
  context: string;
};

export type UpsellsRecommendData = {
  _DATA: any;
};

export type UpsellsWeeklyOpportunitiesInputs = {
};

export type UpsellsWeeklyOpportunitiesData = {
  _DATA: any;
};
