// This file is auto-generated by scripts/generate-warp-types.js

export type MailchimpAddSubscriberInputs = {
  LIST_ID: string;
  email_address: string;
  status: string;
};

export type MailchimpAddSubscriberData = {
  ID: any;
  EMAIL: any;
  STATUS: string;
};

export type MailchimpCreateCampaignInputs = {
  type: string;
  subject_line: string;
  reply_to: string;
  from_name: string;
};

export type MailchimpCreateCampaignData = {
  CAMPAIGN_ID: any;
  STATUS: string;
};
