// This file is auto-generated by scripts/generate-warp-types.js

export type MailchimpCreateCampaignInputs = {
  type: string;
  subject_line: string;
  reply_to: string;
  from_name: string;
};

export type MailchimpCreateCampaignData = {
  CAMPAIGN_ID: any;
  STATUS: string;
};
