// This file is auto-generated by scripts/generate-warp-types.js

export type PipedriveAddPersonInputs = {
  api_token: string;
  name: string;
  email: string;
  phone: string;
};

export type PipedriveAddPersonData = {
  PERSON_ID: any;
  NAME: any;
};
