// This file is auto-generated by scripts/generate-warp-types.js

export type PipedriveAddDealInputs = {
  title: string;
  person_id: number;
  value: string;
  currency: string;
};

export type PipedriveAddDealData = {
  DEAL_ID: any;
  TITLE: any;
};

export type PipedriveAddPersonInputs = {
  name: string;
  email: string;
  phone: string;
};

export type PipedriveAddPersonData = {
  PERSON_ID: any;
  NAME: any;
};
