// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           17
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    shop
    (
        init => init
        upgrade => upgrade
        registerShop => register_shop
        updateShop => update_shop
        getServiceWithPayment => get_service_with_payment
        getShopInfo => get_shop_info
        getShopCount => get_shop_count
        getShops => get_shops
        getShopsByCategory => get_shops_by_category
        addService => add_service
        removeService => remove_service
        getService => get_service
        getServices => get_services
        addProduct => add_product
        updateProductStock => update_product_stock
        removeProduct => remove_product
        getProducts => get_products
        setPaymentDestination => set_payment_destination
        getPaymentDestination => get_payment_destination
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
