// This file is auto-generated by scripts/generate-warp-types.js

export type TikTokGetPublishStatusInputs = {
  publish_id: string;
};

export type TikTokGetPublishStatusData = {
  STATUS: string;
};

export type TikTokGetUserInfoInputs = {
  fields: string;
};

export type TikTokGetUserInfoData = {
  USERNAME: any;
  DISPLAY_NAME: any;
  BIO: any;
  FOLLOWERS: any;
  FOLLOWING: any;
  LIKES: any;
  VIDEOS: any;
  AVATAR: any;
  VERIFIED: any;
};

export type TikTokGetVideoDetailsInputs = {
  VIDEO_IDS: string;
  filters: string;
  fields: string;
};

export type TikTokGetVideoDetailsData = {
  VIDEOS: any;
};

export type TikTokListVideoCommentsInputs = {
  business_id: string;
  video_id: string;
  page_size: number;
  cursor: string;
};

export type TikTokListVideoCommentsData = {
  COMMENTS: any;
  HAS_MORE: boolean;
  CURSOR: any;
};

export type TikTokListVideosInputs = {
  max_count: number;
  cursor: number;
  fields: string;
};

export type TikTokListVideosData = {
  VIDEOS: any;
  HAS_MORE: boolean;
  CURSOR: any;
};

export type TikTokPublishVideoInputs = {
  TITLE: string;
  VIDEO_URL: string;
  PRIVACY: string;
  post_info: string;
  source_info: string;
};

export type TikTokPublishVideoData = {
  PUBLISH_ID: any;
};

export type TikTokReplytoCommentInputs = {
  business_id: string;
  video_id: string;
  comment_id: string;
  text: string;
};

export type TikTokReplytoCommentData = {
  COMMENT_ID: any;
};

export type TikTokUploadVideoDraftInputs = {
  TITLE: string;
  VIDEO_URL: string;
  post_info: string;
  source_info: string;
  post_mode: string;
};

export type TikTokUploadVideoDraftData = {
  PUBLISH_ID: any;
};
