// This file is auto-generated by scripts/generate-warp-types.js

export type MultiversXIssueFungibleESDTTokenInputs = {
  TOKEN_NAME: string;
  TOKEN_TICKER: string;
  INITIAL_SUPPLY: string;
  DECIMALS: string;
};

export type MultiversXIssueFungibleESDTTokenData = {
  TX_HASH: string;
  TOKEN_ID: any;
  TOKEN_NAME: any;
  TOKEN_TICKER: any;
};
