// This file is auto-generated by scripts/generate-warp-types.js

export type AppleMusicSearchInputs = {
  term: string;
  types: string;
  storefront: string;
  limit: number;
};

export type AppleMusicSearchData = {
  SONGS: any;
  ARTISTS: any;
  ALBUMS: any;
};
