// This file is auto-generated by scripts/generate-warp-types.js

export type JoAiListActionItemsInputs = {
  status: string;
  dueToday: boolean;
  priority: string;
};

export type JoAiListActionItemsData = {
  items: any;
  itemsList: any;
  itemsCount: any;
};
