// This file is auto-generated by scripts/generate-warp-types.js

export type CalcomCancelBookingInputs = {
  bookingUid: string;
  cancellationReason: string;
};

export type CalcomCancelBookingData = {
  BOOKING_UID: any;
  BOOKING_STATUS: any;
};

export type CalcomCreateBookingInputs = {
  eventTypeId: number;
  start: string;
  attendeeName: string;
  attendeeEmail: string;
  attendeeTimeZone: string;
  guests: string;
  notes: string;
};

export type CalcomCreateBookingData = {
  BOOKING_UID: any;
  BOOKING_STATUS: any;
  MEETING_URL: any;
};

export type CalcomGetAvailableSlotsInputs = {
  eventTypeId: number;
  start: string;
  end: string;
  timeZone: string;
  duration: number;
};

export type CalcomGetAvailableSlotsData = {
  SLOTS: any;
};

export type CalcomGetBookingInputs = {
  bookingUid: string;
};

export type CalcomGetBookingData = {
  BOOKING_UID: any;
  BOOKING_STATUS: any;
  BOOKING_START: any;
  BOOKING_END: any;
  MEETING_URL: any;
};

export type CalcomListBookingsInputs = {
  status: string;
  eventTypeId: number;
  afterStart: string;
  take: number;
};

export type CalcomListBookingsData = {
  BOOKINGS: any;
  COUNT: any;
};

export type CalcomListEventTypesInputs = {
};

export type CalcomListEventTypesData = {
  EVENT_TYPES: any;
  COUNT: any;
};

export type CalcomRescheduleBookingInputs = {
  bookingUid: string;
  start: string;
  reschedulingReason: string;
};

export type CalcomRescheduleBookingData = {
  BOOKING_UID: any;
  BOOKING_STATUS: any;
  MEETING_URL: any;
};
