// This file is auto-generated by scripts/generate-warp-types.js

export type ZoomCreateMeetingInputs = {
  topic: string;
  type: number;
  start_time: string;
  duration: number;
  password: string;
};

export type ZoomCreateMeetingData = {
  MEETING_ID: any;
  JOIN_URL: any;
  START_URL: any;
};
