// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct ShopContractProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for ShopContractProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = ShopContractProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        ShopContractProxyMethods { wrapped_tx: tx }
    }
}

pub struct ShopContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> ShopContractProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ShopContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ShopContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn register_shop<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerShop")
            .argument(&slug)
            .original_result()
    }

    pub fn get_shop_info<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        slug: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ShopInfo<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getShopInfo")
            .argument(&slug)
            .original_result()
    }

    pub fn add_service<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<u64>,
        Arg4: ProxyArg<u32>,
        Arg5: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        shop_slug: Arg0,
        service_slug: Arg1,
        name: Arg2,
        price_cents: Arg3,
        duration_minutes: Arg4,
        category: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("addService")
            .argument(&shop_slug)
            .argument(&service_slug)
            .argument(&name)
            .argument(&price_cents)
            .argument(&duration_minutes)
            .argument(&category)
            .original_result()
    }

    pub fn remove_service<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        shop_slug: Arg0,
        service_slug: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("removeService")
            .argument(&shop_slug)
            .argument(&service_slug)
            .original_result()
    }

    pub fn get_services<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        shop_slug: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, ShopService<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getServices")
            .argument(&shop_slug)
            .original_result()
    }
}

#[type_abi]
#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode)]
pub struct ShopInfo<Api>
where
    Api: ManagedTypeApi,
{
    pub owner: ManagedAddress<Api>,
    pub created_at: u64,
}

#[type_abi]
#[derive(NestedEncode, NestedDecode, TopEncode, TopDecode)]
pub struct ShopService<Api>
where
    Api: ManagedTypeApi,
{
    pub slug: ManagedBuffer<Api>,
    pub name: ManagedBuffer<Api>,
    pub price_cents: u64,
    pub duration_minutes: u32,
    pub category: ManagedBuffer<Api>,
}
