// This file is auto-generated by scripts/generate-warp-types.js

export type JoAiListProductsInputs = {
  team: string;
};

export type JoAiListProductsData = {
  products: any;
  productsList: any;
};
