// This file is auto-generated by scripts/generate-warp-types.js

export type OneNoteCreatePageInputs = {
  content: string;
};

export type OneNoteCreatePageData = {
  PAGE_ID: any;
  WEB_URL: any;
};

export type MicrosoftToDoCreateTaskInputs = {
  LIST_ID: string;
  title: string;
};

export type MicrosoftToDoCreateTaskData = {
  TASK_ID: any;
  TITLE: any;
};

export type MicrosoftToDoListListsInputs = {
};

export type MicrosoftToDoListListsData = {
  LISTS: any;
};

export type MicrosoftSendEmailInputs = {
  to: string;
  subject: string;
  content: string;
  contentType: string;
};

export type MicrosoftSendEmailData = {
  STATUS: string;
};
