// This file is auto-generated by scripts/generate-warp-types.js

export type MicrosoftSendEmailInputs = {
  to: string;
  subject: string;
  content: string;
  contentType: string;
};

export type MicrosoftSendEmailData = {
  STATUS: string;
};
