// This file is auto-generated by scripts/generate-warp-types.js

export type JupiterSwapQuoteInputs = {
  INPUT_MINT: string;
  OUTPUT_MINT: string;
  AMOUNT: string;
  SLIPPAGE_BPS: string;
};

export type JupiterSwapQuoteData = {
  OUT_AMOUNT: number;
  IN_AMOUNT: number;
  PRICE_IMPACT: any;
  SWAP_USD_VALUE: any;
  SLIPPAGE_BPS: any;
  OTHER_AMOUNT_THRESHOLD: any;
  SWAP_MODE: any;
  ROUTE_COUNT: number;
};

export type JupiterTokenPriceInputs = {
  TOKEN_MINT: string;
};

export type JupiterTokenPriceData = {
  TOKEN_DATA: number;
  USD_PRICE: number;
  DECIMALS: any;
  PRICE_CHANGE_24H: any;
  LIQUIDITY: any;
  PRICE_FORMATTED: number;
};
