// This file is auto-generated by scripts/generate-warp-types.js

export type JoAiUpdateStatsInputs = {
  team: string;
};

export type JoAiUpdateStatsData = {
  DEALS_COUNT: number;
  EVENTS_COUNT: number;
  NEWS_COUNT: number;
};
