// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           14
// Async Callback:                       1
// Total number of exported functions:  17

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    certificate
    (
        init => init
        upgrade => upgrade
        createCollection => create_collection
        issue => issue
        claim => claim
        revoke => revoke
        getCollection => get_collection
        getCollectionToken => get_collection_token
        isCollectionReady => is_collection_ready
        getCollectionsByIssuer => get_collections_by_issuer
        getCertificate => get_certificate
        isValid => is_valid
        getCertsByIssuer => get_certs_by_issuer
        getCertsByCollection => get_certs_by_collection
        getNextCertId => get_next_cert_id
        getNextCollectionId => get_next_collection_id_view
    )
}

multiversx_sc_wasm_adapter::async_callback! { certificate }
