// This file is auto-generated by scripts/generate-warp-types.js

export type TypefullyCreateScheduleDraftInputs = {
  content: string;
  threadify: boolean;
  share: boolean;
  'schedule-date': string;
  auto_retweet_enabled: boolean;
  auto_plug_enabled: boolean;
};
