// This file is auto-generated by scripts/generate-warp-types.js

export type TypefullyCreateScheduleDraftInputs = {
  content: string;
  threadify: string;
  share: string;
  'schedule-date': string;
  auto_retweet_enabled: string;
  auto_plug_enabled: string;
};

