// This file is auto-generated by scripts/generate-warp-types.js

export type LaravelCloudListLogsInputs = {
  ENVIRONMENT_ID: string;
};

export type LaravelCloudListLogsData = {
  COUNT: number;
  LOGS: any[];
};
