// This file is auto-generated by scripts/generate-warp-types.js

export type FollowupsBirthdayScanInputs = {
};

export type FollowupsBirthdayScanData = {
  CONTACTS: any;
};

export type FollowupsBirthdayInputs = {
  contactId: string;
  offer: string;
  integration: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type FollowupsBirthdayData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type FollowupsCheckInInputs = {
  contactId: string;
  lastVisitDate: string;
  integration: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type FollowupsCheckInData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type FollowupsEnrollContactInputs = {
  contactId: string;
  followups_sequence: string;
  key: string;
  followups_step: string;
  tag: string;
};

export type FollowupsExecuteStepInputs = {
  contactId: string;
  sequenceSlug: string;
  integration: string;
  recipientId: string;
  recipientName: string;
  message: string;
  value: string;
  key: string;
};

export type FollowupsExecuteStepData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
  TEMPLATE_CONTENT: any;
  TEMPLATE_CHANNEL: any;
  TEMPLATE_SLUG: any;
  TEMPLATE_STEP: any;
};

export type FollowupsHandleReplyInputs = {
  contactId: string;
  tag: string;
  type: string;
  description: string;
  followups: boolean;
  event: string;
};

export type FollowupsInactiveScanInputs = {
};

export type FollowupsInactiveScanData = {
  _DATA: any;
};

export type FollowupsPostTreatmentInputs = {
  contactId: string;
  treatment: string;
  integration: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type FollowupsPostTreatmentData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type FollowupsReorderReminderInputs = {
  contactId: string;
  productName: string;
  lastPurchased: string;
  integration: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type FollowupsReorderReminderData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};

export type FollowupsCreateTemplateInputs = {
  title: string;
  content: string;
  slug: string;
  channel: string;
  step: string;
  delay_days: string;
  variables: string;
};

export type FollowupsWinBackInputs = {
  contactId: string;
  daysInactive: string;
  offer: string;
  integration: string;
  recipientId: string;
  recipientName: string;
  message: string;
};

export type FollowupsWinBackData = {
  CONTACT_NAME: any;
  CONTACT_PHONE: any;
  CONTACT_EMAIL: any;
};
