// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleDriveCreateFolderInputs = {
  name: string;
  mimeType: string;
  parentId: string;
};

export type GoogleDriveCreateFolderData = {
  FOLDER_ID: any;
  FOLDER_NAME: any;
};

export type GoogleDriveListFilesInputs = {
  pageSize: number;
  q: string;
};

export type GoogleDriveListFilesData = {
  FILES: any;
  NEXT_PAGE_TOKEN: any;
};
