// This file is auto-generated by scripts/generate-warp-types.js

export type GoogleDriveListFilesInputs = {
  pageSize: number;
  q: string;
};

export type GoogleDriveListFilesData = {
  FILES: any;
  NEXT_PAGE_TOKEN: any;
};
