// This file is auto-generated by scripts/generate-warp-types.js

export type WorkOrderCreateBillInputs = {
  contactId: string;
  items: string;
  fresh: boolean;
};

export type WorkOrderCreateBillData = {
  id: any;
  total: any;
  totalDisplay: number;
  invoiceUrl: any;
  paymentUrl: any;
  status: any;
};

export type WorkOrderCreateInputs = {
  customer: string;
  work: string;
  hours: number;
  materials: string;
};
